import type { AIChatRequest, AIChatResponse, AIImageGenerationRequest, AIImageGenerationResponse, AIModelCatalogEntry, AIProviderAdapter, AIProviderRecord, AIStreamChunk, AIVideoGenerationRequest, AIVideoGenerationResponse } from "./ai-provider.types";
import { logger } from "../lib/logger";

const OPENAI_BASE = "https://integrate.api.nvidia.com/v1";
const GENAI_BASE = "https://ai.api.nvidia.com/v1/genai";
const keyFor = (provider: AIProviderRecord, key?: string) => { const value = key?.trim() || process.env[provider.apiKeyEnv]?.trim(); if (!value) throw new Error(`${provider.apiKeyEnv} is not configured`); return value; };
const trimUrl = (value: string) => value.replace(/\/+$/, "");
const mime = (b: Buffer) => b.length >= 12 && b.subarray(4, 8).toString("ascii") === "ftyp" ? "video/mp4" : b.length >= 4 && b.subarray(0, 4).equals(Buffer.from([0x1a, 0x45, 0xdf, 0xa3])) ? "video/webm" : b.length >= 8 && b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) ? "image/png" : b.length >= 3 && b.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff])) ? "image/jpeg" : "application/octet-stream";
const decode = (value: unknown): Buffer | undefined => { if (typeof value !== "string" || !value.trim()) return undefined; const s = value.trim(); const i = s.indexOf(","); try { return Buffer.from(s.startsWith("data:") && i >= 0 ? s.slice(i + 1) : s, "base64"); } catch { return undefined; } };
async function fail(response: Response): Promise<never> { const body = await response.text().catch(() => ""); throw new Error(`nvidia request failed (${response.status})${body ? `: ${body.slice(0, 1200)}` : ""}`); }
function usage(u: any) { if (!u) return undefined; const r: any = {}; const i = Number(u.prompt_tokens ?? u.input_tokens ?? NaN), o = Number(u.completion_tokens ?? u.output_tokens ?? NaN), t = Number(u.total_tokens ?? NaN); if (Number.isFinite(i)) r.inputTokens = i; if (Number.isFinite(o)) r.outputTokens = o; if (Number.isFinite(t)) r.totalTokens = t; return Object.keys(r).length ? r : undefined; }
function configured(): AIModelCatalogEntry[] { const image = [process.env.NVIDIA_IMAGE_MODEL, ...(process.env.NVIDIA_IMAGE_MODEL_POOL || "").split(",")].filter((v): v is string => Boolean(v?.trim())).map(v => ({ provider: "nvidia" as const, modelId: v.trim(), name: v.trim(), status: "active" as const, capabilities: ["image_generation"], source: "registry" as const })); const video = [process.env.NVIDIA_VIDEO_MODEL, ...(process.env.NVIDIA_VIDEO_MODEL_POOL || "").split(",")].filter((v): v is string => Boolean(v?.trim())).map(v => ({ provider: "nvidia" as const, modelId: v.trim(), name: v.trim(), status: "active" as const, capabilities: ["video_generation"], source: "registry" as const })); return [...new Map([...image, ...video].map(x => [x.modelId, x])).values()]; }

export class NvidiaProviderAdapter implements AIProviderAdapter {
  readonly providerId = "nvidia" as const;
  async chat(request: AIChatRequest, provider: AIProviderRecord, apiKey?: string): Promise<AIChatResponse> { const r = await fetch(`${trimUrl(provider.baseUrl || OPENAI_BASE)}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${keyFor(provider, apiKey)}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: request.model, messages: request.messages, stream: false, ...(request.temperature !== undefined ? { temperature: request.temperature } : {}), ...(request.topP !== undefined ? { top_p: request.topP } : {}), ...(request.maxOutputTokens !== undefined ? { max_tokens: request.maxOutputTokens } : {}) }) }); if (!r.ok) await fail(r); const p: any = await r.json(); return { provider: this.providerId, model: request.model, text: p.choices?.[0]?.message?.content || "", finishReason: p.choices?.[0]?.finish_reason, usage: usage(p.usage), raw: p }; }
  async *stream(request: AIChatRequest, provider: AIProviderRecord, apiKey?: string): AsyncGenerator<AIStreamChunk> { const r = await fetch(`${trimUrl(provider.baseUrl || OPENAI_BASE)}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${keyFor(provider, apiKey)}`, "Content-Type": "application/json", Accept: "text/event-stream" }, body: JSON.stringify({ model: request.model, messages: request.messages, stream: true, ...(request.temperature !== undefined ? { temperature: request.temperature } : {}), ...(request.topP !== undefined ? { top_p: request.topP } : {}), ...(request.maxOutputTokens !== undefined ? { max_tokens: request.maxOutputTokens } : {}) }) }); if (!r.ok) await fail(r); if (!r.body) throw new Error("NVIDIA returned an empty stream"); const reader = r.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; try { while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const events = buffer.split(/\r?\n\r?\n/); buffer = events.pop() || ""; for (const event of events) { const data = event.split(/\r?\n/).filter(x => x.startsWith("data:")).map(x => x.slice(5).trim()).join(""); if (!data || data === "[DONE]") continue; const p: any = JSON.parse(data), c = p.choices?.[0], delta = typeof c?.delta?.content === "string" ? c.delta.content : ""; if (!delta && !c?.finish_reason) continue; yield { provider: this.providerId, model: request.model, delta, done: Boolean(c?.finish_reason), finishReason: c?.finish_reason, usage: usage(p.usage) }; } } } finally { reader.releaseLock(); } }
  async test(model: string, provider: AIProviderRecord, apiKey?: string) { const started = Date.now(); try { await this.chat({ model, messages: [{ role: "user", content: "ping" }], maxOutputTokens: 4 }, provider, apiKey); return { ok: true, latencyMs: Date.now() - started }; } catch (error) { return { ok: false, latencyMs: Date.now() - started, error: error instanceof Error ? error.message : String(error) }; } }
  async listModels(provider: AIProviderRecord, apiKey?: string): Promise<AIModelCatalogEntry[]> { const local = configured(); try { const r = await fetch(`${trimUrl(provider.baseUrl || OPENAI_BASE)}/models`, { headers: { Authorization: `Bearer ${keyFor(provider, apiKey)}`, Accept: "application/json" } }); if (!r.ok) return local; const p: any = await r.json(); const chat = (Array.isArray(p?.data) ? p.data : []).filter((x: any) => typeof x?.id === "string").map((x: any) => ({ provider: "nvidia" as const, modelId: x.id, name: x.id, status: "active" as const, capabilities: ["chat", "streaming"], source: "provider_api" as const })); return [...new Map([...chat, ...local].map(x => [x.modelId, x])).values()]; } catch (error) { logger.warn({ error: String(error) }, "NVIDIA model discovery failed; returning configured media models"); return local; } }
  async generateImage(request: AIImageGenerationRequest, provider: AIProviderRecord, apiKey?: string): Promise<AIImageGenerationResponse> { const model = request.model?.trim(); if (!model) throw new Error("NVIDIA image generation requires a resolved model"); const width = Number.isFinite(request.width) && request.width! > 0 ? Math.floor(request.width!) : 1024; const height = Number.isFinite(request.height) && request.height! > 0 ? Math.floor(request.height!) : 1024; const r = await fetch(`${trimUrl(process.env.NVIDIA_IMAGE_BASE_URL?.trim() || GENAI_BASE)}/${model}`, { method: "POST", headers: { Authorization: `Bearer ${keyFor(provider, apiKey)}`, "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ prompt: request.prompt, width, height, samples: 1 }) }); if (!r.ok) await fail(r); const p: any = await r.json(); const b = decode(p?.data?.[0]?.b64_json || p?.data?.[0]?.image || p?.b64_json || p?.image); if (!b || b.length <= 2000 || !mime(b).startsWith("image/")) throw new Error("NVIDIA returned an invalid image payload"); return { provider: this.providerId, route: "inference_provider", model, buffer: b, mimeType: mime(b), fallbackUsed: false, raw: p }; }
  async generateVideo(request: AIVideoGenerationRequest, provider: AIProviderRecord, apiKey?: string): Promise<AIVideoGenerationResponse> { const model = request.model?.trim(); if (!model) throw new Error("NVIDIA video generation requires a resolved model"); const endpoint = process.env.NVIDIA_VIDEO_ENDPOINT?.trim() || `${trimUrl(process.env.NVIDIA_VIDEO_BASE_URL?.trim() || GENAI_BASE)}/${model}`; const r = await fetch(endpoint, { method: "POST", headers: { Authorization: `Bearer ${keyFor(provider, apiKey)}`, "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ prompt: request.prompt, resolution: process.env.NVIDIA_VIDEO_RESOLUTION?.trim() || "480", num_output_frames: Number(process.env.NVIDIA_VIDEO_FRAMES || 121), fps: Number(process.env.NVIDIA_VIDEO_FPS || 24), steps: Number(process.env.NVIDIA_VIDEO_STEPS || 35) }) }); if (!r.ok) await fail(r); const p: any = await r.json(); const b = decode(p?.b64_video || p?.video || p?.data?.[0]?.b64_video || p?.data?.[0]?.video); if (!b || b.length <= 2000 || !mime(b).startsWith("video/")) throw new Error("NVIDIA returned an invalid video payload"); return { provider: this.providerId, route: "inference_provider", model, buffer: b, mimeType: mime(b), fallbackUsed: false, raw: p }; }
}
export const nvidiaProviderAdapter = new NvidiaProviderAdapter();