import { Router, type IRouter } from "express";
import healthRouter from "./health";
import keysRouter from "./keys";
import providerKeysRouter from "./provider-keys";
import dashboardRouter from "./dashboard";
import envRouter from "./env";
import executionRouter from "./execution";
import modelsRouter from "./models";
import providersRouter from "./providers";
import aiRoutingRouter from "./ai-routing";
import simulatorRouter from "./simulator";
import behaviorConfigRouter from "./behavior-config";
import proactiveAssistantRouter from "./proactive-assistant";
import mediaStorageRouter from "./media-storage";
import knowledgeRouter from "./knowledge";
import userAccessRouter from "./user-access";
import personasRouter from "./personas";
import diagnosticsRouter from "./diagnostics";
import authRouter from "./auth";
import userRouter from "./user";
import reactionThemeRouter from "./reaction-theme";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/user", userRouter);
router.use(reactionThemeRouter);
router.use(keysRouter);
router.use(providerKeysRouter);
router.use(dashboardRouter);
router.use(envRouter);
router.use(executionRouter);
router.use(modelsRouter);
router.use(providersRouter);
router.use(aiRoutingRouter);
router.use(simulatorRouter);
router.use(behaviorConfigRouter);
router.use(proactiveAssistantRouter);
router.use(mediaStorageRouter);
router.use(knowledgeRouter);
router.use(userAccessRouter);
router.use(personasRouter);
router.use(diagnosticsRouter);

export default router;
