export function renderDashboardMediaModelControls(): string {
  return String.raw`
<style>
.wb-media-manager{margin-top:0}.wb-media-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.wb-media-tab{border:1px solid var(--line);background:var(--panel);color:var(--muted);padding:9px 12px;border-radius:9px;cursor:pointer}.wb-media-tab.active{background:#145aa0;border-color:#2a78ca;color:var(--text)}.wb-media-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:12px}.wb-media-stat{padding:11px;border:1px solid var(--line);border-radius:10px;background:#0a1626}.wb-media-stat strong{display:block;font-size:18px}.wb-media-stat span{display:block;color:var(--muted);font-size:11px;margin-top:2px}.wb-media-card{display:grid;grid-template-columns:1fr auto;gap:12px;padding:13px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.wb-media-card.preferred{border-color:#2a78ca;box-shadow:0 0 0 1px rgba(42,120,202,.2) inset}.wb-media-meta{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.wb-media-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.wb-media-form{display:grid;grid-template-columns:1fr 1.7fr 1fr 110px auto;gap:8px;margin-top:10px}.wb-media-note{font-size:11px;color:var(--muted);margin-top:7px}.wb-media-catalog{font-size:11px;color:var(--muted);margin-top:7px}.wb-media-hidden{display:none!important}@media(max-width:900px){.wb-media-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.wb-media-form{grid-template-columns:1fr 1fr}.wb-media-form .wb-media-actions{grid-column:1/-1;justify-content:flex-start}}@media(max-width:600px){.wb-media-summary{grid-template-columns:1fr}.wb-media-form{grid-template-columns:1fr}.wb-media-card{grid-template-columns:1fr}.wb-media-actions{justify-content:flex-start}}
</style>
<script>
(function(){
  const CAPABILITIES={image_generation:{label:'Image',task:'text-to-image',icon:'🖼️'},video_generation:{label:'Video',task:'text-to-video',icon:'🎬'}};
  let activeCapability='image_generation'; let models=[]; let providers=[]; let catalog=[]; let editingId=null;
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
  function toast(msg,bad){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.style.display='block';clearTimeout(window.__wbMediaToast);window.__wbMediaToast=setTimeout(()=>el.style.display='none',4200);if(bad)el.style.borderColor='rgba(255,102,117,.4)'}
  async function api(url,options){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function currentProviders(){return providers.filter(p=>p.enabled)}
  function setCapability(capability){activeCapability=capability;editingId=null;renderTabs();loadMediaModels();loadCatalog();clearEditor()}
  function renderTabs(){document.querySelectorAll('[data-media-capability]').forEach(b=>b.classList.toggle('active',b.dataset.mediaCapability===activeCapability));const label=CAPABILITIES[activeCapability].label;const title=document.getElementById('wbMediaTitle');if(title)title.textContent=label+' Models'}
  function renderSummary(){const enabled=models.filter(m=>m.enabled!==false);const providersCount=new Set(enabled.map(m=>m.provider)).size;const preferred=enabled.slice().sort((a,b)=>(a.priority??0)-(b.priority??0))[0];document.getElementById('wbMediaCount').textContent=models.length;document.getElementById('wbMediaEnabled').textContent=enabled.length;document.getElementById('wbMediaProviders').textContent=providersCount;document.getElementById('wbMediaPreferred').textContent=preferred?preferred.modelId:'—'}
  function renderList(){const list=document.getElementById('wbMediaList');if(!models.length){list.innerHTML='<div class="empty">No '+CAPABILITIES[activeCapability].label.toLowerCase()+' models are registered. Discover a live catalog and register one below.</div>';renderSummary();return}const minPriority=Math.min(...models.map(m=>Number.isFinite(m.priority)?m.priority:0));list.innerHTML=models.slice().sort((a,b)=>(a.priority??0)-(b.priority??0)).map(m=>{const enabled=m.enabled!==false;const preferred=enabled&&m.priority===minPriority;return '<div class="wb-media-card '+(preferred?'preferred':'')+'"><div><strong>'+esc(m.name||m.modelId)+'</strong> '+(preferred?'<span class="pill good">Preferred candidate</span>':'')+'<div class="mono" style="font-size:12px;color:var(--blue);margin-top:3px">'+esc(m.provider)+' / '+esc(m.modelId)+'</div><div class="wb-media-meta"><span class="pill">'+esc(CAPABILITIES[activeCapability].label)+'</span><span class="pill '+(enabled?'good':'bad')+'">'+(enabled?'Enabled':'Disabled')+'</span><span class="pill">Priority '+esc(m.priority)+'</span></div></div><div class="wb-media-actions"><button class="btn primary" '+(preferred?'disabled':'')+' data-media-preferred="'+esc(m.id)+'">'+(preferred?'Preferred':'Prefer')+'</button><button class="btn" data-media-test="'+esc(m.id)+'">Test generation</button><button class="btn" data-media-edit="'+esc(m.id)+'">Edit</button><button class="btn" data-media-toggle="'+esc(m.id)+'" data-enabled="'+enabled+'">'+(enabled?'Disable':'Enable')+'</button><button class="btn danger" data-media-delete="'+esc(m.id)+'">Delete</button></div></div>'}).join('');renderSummary()}
  async function loadProviders(){const d=await api('/api/providers');providers=d.providers||[];const select=document.getElementById('wbMediaProvider');const selected=select.value;select.innerHTML=currentProviders().map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name||p.id)+'</option>').join('');if(selected&&currentProviders().some(p=>p.id===selected))select.value=selected;updateProviderNote()}
  async function loadMediaModels(){try{const d=await api('/api/media-models?capability='+encodeURIComponent(activeCapability));models=d.models||[];renderList()}catch(e){document.getElementById('wbMediaList').innerHTML='<div class="empty">Unable to load media registry: '+esc(e.message)+'</div>';toast(e.message,true)}}
  async function loadCatalog(force=false){const provider=document.getElementById('wbMediaProvider').value;if(!provider)return;document.getElementById('wbMediaCatalogStatus').textContent='Discovering current '+CAPABILITIES[activeCapability].label.toLowerCase()+' models…';try{const d=await api('/api/media-models/catalog/'+encodeURIComponent(provider)+'?capability='+encodeURIComponent(activeCapability)+(force?'&refresh=true':''));catalog=d.models||[];populateModelSelect();document.getElementById('wbMediaCatalogStatus').textContent=catalog.length+' live '+CAPABILITIES[activeCapability].label.toLowerCase()+' models available';}catch(e){catalog=[];populateModelSelect();document.getElementById('wbMediaCatalogStatus').textContent='Catalog unavailable: '+e.message}}
  function populateModelSelect(){const select=document.getElementById('wbMediaModelId');const current=select.value;select.innerHTML=catalog.map(m=>'<option value="'+esc(m.modelId)+'">'+esc(m.name||m.modelId)+' · '+esc(m.modelId)+'</option>').join('')||'<option value="">No live models available</option>';if(current&&catalog.some(m=>m.modelId===current))select.value=current;updateCatalogMeta()}
  function updateCatalogMeta(){const model=catalog.find(m=>m.modelId===document.getElementById('wbMediaModelId').value);document.getElementById('wbMediaCatalogMeta').textContent=model?'Live provider catalog · '+esc((model.capabilities||[]).join(', ')||'capability verified'):'Select a live model from the catalog.'}
  function updateProviderNote(){const p=providers.find(x=>x.id===document.getElementById('wbMediaProvider').value);document.getElementById('wbMediaProviderNote').textContent=p?(p.configured?'Connected · provider key available':p.enabled?'Enabled · add a Dashboard-managed key to discover protected catalog models':'Provider disabled'):''}
  function clearEditor(){editingId=null;document.getElementById('wbMediaEditorTitle').textContent='Register '+CAPABILITIES[activeCapability].label.toLowerCase()+' model';document.getElementById('wbMediaSave').textContent='Register & Save';document.getElementById('wbMediaCancel').style.display='none';document.getElementById('wbMediaModelName').value='';document.getElementById('wbMediaPriority').value='';document.getElementById('wbMediaProviderNote').textContent='';}
  function beginEdit(id){const m=models.find(x=>x.id===id);if(!m)return;editingId=id;document.getElementById('wbMediaProvider').value=m.provider;document.getElementById('wbMediaModelName').value=m.name||'';document.getElementById('wbMediaPriority').value=Number.isFinite(m.priority)?m.priority:'';loadCatalog().finally(()=>{document.getElementById('wbMediaModelId').value=m.modelId;document.getElementById('wbMediaEditorTitle').textContent='Edit '+CAPABILITIES[activeCapability].label.toLowerCase()+' model';document.getElementById('wbMediaSave').textContent='Save changes';document.getElementById('wbMediaCancel').style.display='inline-flex';updateCatalogMeta()})}
  async function save(){const provider=document.getElementById('wbMediaProvider').value;const modelId=document.getElementById('wbMediaModelId').value.trim();const name=document.getElementById('wbMediaModelName').value.trim();const priority=Number(document.getElementById('wbMediaPriority').value);if(!provider||!modelId){toast('Select a provider and live model');return}try{if(editingId){await api('/api/media-models/'+encodeURIComponent(editingId),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,priority:Number.isFinite(priority)?priority:undefined})});toast('✓ Media model updated')}else{await api('/api/media-models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,modelId,name,priority:Number.isFinite(priority)?priority:undefined,capability:activeCapability})});toast('✓ Media model registered')}clearEditor();await loadMediaModels()}catch(e){toast('Save failed: '+e.message,true)}}
  document.addEventListener('click',async e=>{const t=e.target;if(!(t instanceof Element))return;if(t.matches('[data-media-capability]')){setCapability(t.dataset.mediaCapability);return}if(t.matches('[data-media-refresh]')){await loadCatalog(true);return}if(t.matches('[data-media-preferred]')){try{await api('/api/media-models/'+encodeURIComponent(t.dataset.mediaPreferred)+'/preferred',{method:'POST'});await loadMediaModels();toast('✓ Preferred media candidate updated')}catch(err){toast(err.message,true)}return}if(t.matches('[data-media-edit]')){beginEdit(t.dataset.mediaEdit);return}if(t.matches('[data-media-test]')){try{const d=await api('/api/media-models/'+encodeURIComponent(t.dataset.mediaTest)+'/test',{method:'POST'});toast('✓ '+d.capability+' generation succeeded via '+d.provider+'/'+d.model+' ('+d.latencyMs+'ms)')}catch(err){toast('Media generation test failed: '+err.message,true)}return}if(t.matches('[data-media-toggle]')){try{await api('/api/media-models/'+encodeURIComponent(t.dataset.mediaToggle),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:t.dataset.enabled!=='true'})});await loadMediaModels();toast('Media model state updated')}catch(err){toast(err.message,true)}return}if(t.matches('[data-media-delete]')){if(!confirm('Remove this media model from the registry?'))return;try{await api('/api/media-models/'+encodeURIComponent(t.dataset.mediaDelete),{method:'DELETE'});await loadMediaModels();toast('Media model removed')}catch(err){toast(err.message,true)}}});
  document.addEventListener('DOMContentLoaded',async()=>{const main=document.querySelector('main');if(!main||document.getElementById('view-media'))return;const section=document.createElement('section');section.className='view';section.id='view-media';section.innerHTML='<div class="card wb-media-manager"><div class="section-head"><div><div class="section-title" id="wbMediaTitle">Image Models</div><div class="section-note">Dashboard control plane for image and video candidates. PostgreSQL is authoritative; the adaptive media runtime consumes enabled registered models.</div></div><button class="btn" onclick="window.__wbMediaRefresh()">Refresh</button></div><div class="wb-media-tabs"><button class="wb-media-tab active" data-media-capability="image_generation">🖼️ Image</button><button class="wb-media-tab" data-media-capability="video_generation">🎬 Video</button></div><div class="wb-media-summary"><div class="wb-media-stat"><strong id="wbMediaCount">0</strong><span>Registered</span></div><div class="wb-media-stat"><strong id="wbMediaEnabled">0</strong><span>Enabled</span></div><div class="wb-media-stat"><strong id="wbMediaProviders">0</strong><span>Providers</span></div><div class="wb-media-stat"><strong id="wbMediaPreferred">—</strong><span>Preferred candidate</span></div></div><div id="wbMediaList" class="stack"></div><div style="border-top:1px solid var(--line);margin-top:14px;padding-top:14px"><div class="section-title" id="wbMediaEditorTitle">Register image model</div><div class="wb-media-form"><select id="wbMediaProvider" class="select"></select><select id="wbMediaModelId" class="select"></select><input id="wbMediaModelName" class="input" placeholder="Display name (optional)"/><input id="wbMediaPriority" class="input" type="number" min="0" placeholder="Priority"/><div class="wb-media-actions"><button id="wbMediaSave" class="btn primary">Register & Save</button><button id="wbMediaCancel" class="btn" style="display:none">Cancel</button></div></div><div class="wb-media-note" id="wbMediaProviderNote"></div><div class="wb-media-catalog" id="wbMediaCatalogMeta"></div><div style="display:flex;gap:8px;align-items:center;margin-top:6px"><span class="wb-media-note" id="wbMediaCatalogStatus">Select a provider to discover its live catalog.</span><button class="btn" data-media-refresh="true" type="button">Refresh catalog</button></div><div class="wb-media-note">Priority is the adaptive candidate ordering for this registered media model. Lower numbers are preferred; the runtime will continue through other enabled candidates after failures.</div></div></div>';main.appendChild(section);
    const nav=document.getElementById('nav');const mobile=document.getElementById('mobileNav');function addNav(container){if(!container||container.querySelector('[data-view="media"]'))return;const b=document.createElement('button');b.dataset.view='media';b.textContent='Media Models';b.onclick=()=>showView('media');container.appendChild(b)}addNav(nav);addNav(mobile);
    document.getElementById('wbMediaProvider').onchange=async()=>{updateProviderNote();await loadCatalog(true)};document.getElementById('wbMediaModelId').onchange=updateCatalogMeta;document.getElementById('wbMediaSave').onclick=save;document.getElementById('wbMediaCancel').onclick=clearEditor;window.__wbMediaRefresh=async()=>{await loadProviders();await loadMediaModels();await loadCatalog(true)};try{await loadProviders();await loadMediaModels();await loadCatalog(false)}catch(e){toast('Media controls initialization failed: '+e.message,true)}});
})();
</script>`;
}
