export function renderDashboardHtml(): string {
  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#07111f" />
  <title>Wingbuddy Control Center</title>
  <style>
    :root{--bg:#07111f;--panel:#0d1a2b;--panel-2:#0f2238;--panel-3:#091524;--line:#1b3049;--line-strong:#2a486c;--text:#e8f0f8;--muted:#8ea2b8;--blue:#5aa7ff;--green:#37d39a;--amber:#f5b74f;--red:#ff6675;--shadow:0 16px 40px rgba(0,0,0,.24);--touch-min:44px}
    *,*:before,*:after{box-sizing:border-box}
    html,body{max-width:100%;overflow-x:hidden}
    body{margin:0;background:radial-gradient(circle at top right,#0f2843 0,#07111f 42%,#040b14 100%);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-text-size-adjust:100%}
    .app{min-height:100vh;display:grid;grid-template-columns:240px minmax(0,1fr)}
    .side{position:sticky;top:0;height:100vh;padding:22px 16px;border-right:1px solid var(--line);background:color-mix(in srgb,var(--panel) 92%,transparent);backdrop-filter:blur(14px);z-index:30}
    .brand{display:flex;align-items:center;gap:10px;padding:10px 8px 18px;font-weight:800;font-size:18px}
    .logo{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:linear-gradient(135deg,#5aa7ff,#8d6cff);flex-shrink:0}
    .nav{display:grid;gap:6px}
    .nav button,.mobile-nav button{border:1px solid transparent;background:transparent;color:var(--muted);min-height:var(--touch-min);padding:10px 12px;border-radius:10px;text-align:left;cursor:pointer;font-size:13.5px;font-weight:500;display:inline-flex;align-items:center;white-space:nowrap;-webkit-tap-highlight-color:transparent}
    .nav button:hover,.nav button.active,.mobile-nav button.active{background:var(--nav-active);color:var(--text);border-color:var(--line-strong)}
    .side-foot{position:absolute;left:16px;right:16px;bottom:18px}
    .health{padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--panel-2);font-size:12px}
    .health strong{display:block;font-size:13px;margin-bottom:4px}
    .mobile-nav{display:none}
    main, div:nth-of-type(1) > div:nth-of-type(1) > main:nth-of-type(1){padding:24px 28px;min-width:0;width:100%;max-width:1440px;margin:0 auto}
    .top{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:20px;flex-wrap:wrap}
    .top>div:first-child{flex:1 1 auto;max-width:900px;min-width:0}
    .eyebrow{font-size:11px;color:var(--blue);font-weight:800;letter-spacing:.12em;text-transform:uppercase}
    .title{margin:3px 0 4px;font-size:28px;letter-spacing:-.03em;word-break:break-word}
    .subtitle{margin:0;color:var(--muted);max-width:900px;line-height:1.5}
    .toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
    .btn{border:1px solid var(--line);background:#0d1a2b;color:var(--text);min-height:var(--touch-min);padding:9px 14px;border-radius:9px;cursor:pointer;font-size:13px;font-weight:600;display:inline-flex;align-items:center;justify-content:center;gap:6px;touch-action:manipulation;-webkit-tap-highlight-color:transparent}
    .btn:hover{border-color:#31567e;background:#102238}
    .btn:active{transform:scale(.98)}
    .btn.primary{background:#145aa0;border-color:#2a78ca}
    .btn.primary:hover{background:#1768b8}
    .btn.danger{background:rgba(255,102,117,.12);color:#ff9aa4;border-color:rgba(255,102,117,.3)}
    .btn.danger:hover{background:rgba(255,102,117,.2)}
    .btn.small{min-height:36px;padding:6px 11px;font-size:12px}
    .view{display:none}
    .view.active{display:block}
    .grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}
    .card{background:linear-gradient(180deg,rgba(16,31,51,.96),rgba(10,22,38,.96));border:1px solid var(--line);border-radius:14px;padding:16px;box-shadow:var(--shadow);min-width:0}
    .label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}
    .value{font-size:22px;font-weight:800;margin-top:4px;word-break:break-word}
    .sub{color:var(--muted);font-size:12px;margin-top:5px;word-break:break-word}
    .section{margin-bottom:16px}
    .section-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px;flex-wrap:wrap}
    .section-head>div:first-child{flex:1 1 auto;min-width:0}
    .section-title{font-size:16px;font-weight:800}
    .section-note{font-size:12px;color:var(--muted)}
    .table-wrap{width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch;border:1px solid var(--line);border-radius:12px;margin-bottom:8px}
    .table{width:100%;border-collapse:collapse;min-width:680px}
    .table th,.table td{padding:11px 12px;border-bottom:1px solid #152a40;text-align:left;vertical-align:middle}
    .table th{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.07em;background:#0a1626;position:sticky;top:0;z-index:2}
    .table tr:last-child td{border-bottom:0}
    .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}
    .pill{display:inline-flex;align-items:center;padding:4px 9px;border-radius:999px;font-size:11px;font-weight:600;border:1px solid var(--line);background:#0b1727;color:var(--muted);white-space:nowrap}
    .pill.good{color:#8de6c0;border-color:rgba(55,211,154,.25);background:rgba(55,211,154,.08)}
    .pill.warn{color:#ffd38c;border-color:rgba(245,183,79,.25);background:rgba(245,183,79,.08)}
    .pill.bad{color:#ff9aa4;border-color:rgba(255,102,117,.25);background:rgba(255,102,117,.08)}
    .status{display:inline-flex;align-items:center;gap:7px;font-weight:700}
    .dot{width:8px;height:8px;border-radius:50%;background:#718096;flex-shrink:0}
    .dot.green{background:var(--green)}
    .dot.amber{background:var(--amber)}
    .cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}
    .mini{padding:12px;border:1px solid var(--line);border-radius:11px;background:var(--panel-2);min-width:0}
    .mini strong{display:block;margin-bottom:3px;word-break:break-word}
    .mini span{color:var(--muted);font-size:12px;word-break:break-word}
    .form-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:center}
    .input,.select{width:100%;min-height:var(--touch-min);border:1px solid var(--line);background:var(--panel-3);color:var(--text);padding:10px 12px;border-radius:9px;outline:none;font-size:14px}
    .input:focus,.select:focus{border-color:var(--blue)}
    .stack{display:grid;gap:9px}
    .split{display:grid;grid-template-columns:1fr 1fr;gap:12px}
    .notice{padding:12px 14px;border-radius:10px;border:1px solid var(--line);background:var(--panel-2);color:var(--muted);font-size:12.5px;line-height:1.5}
    .empty{text-align:center;color:var(--muted);padding:26px}
    .toast{position:fixed;right:18px;bottom:18px;max-width:360px;background:var(--panel);border:1px solid var(--line);color:var(--text);padding:12px 14px;border-radius:11px;display:none;box-shadow:var(--shadow);z-index:100}

    /* Tablet breakpoint (769px to 1199px) */
    @media(max-width:1199px){
      .app{grid-template-columns:200px minmax(0,1fr)}
      .grid{grid-template-columns:repeat(2,minmax(0,1fr))}
      .cards{grid-template-columns:repeat(2,minmax(0,1fr))}
      main{padding:20px}
    }

    /* Mobile breakpoint (<768px down to 320px) */
    @media(max-width:768px){
      .app{display:block}
      .side{display:none}
      .mobile-nav{display:flex;position:sticky;top:0;z-index:40;gap:6px;overflow-x:auto;-webkit-overflow-scrolling:touch;padding:8px 10px;background:color-mix(in srgb,var(--panel) 96%,transparent);border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}
      .mobile-nav::-webkit-scrollbar{display:none}
      .mobile-nav button{flex-shrink:0;padding:8px 12px;font-size:13px}
      main{padding:10px 10px}
      .top{display:flex;flex-direction:column;gap:6px;margin-bottom:10px;height:auto;min-height:0}
      .top>div:first-child{flex:0 0 auto;width:100%;min-width:0;min-height:0;height:auto;margin-bottom:0}
      .eyebrow{font-size:10px}
      .top .toolbar{width:100%;justify-content:flex-start;margin-top:2px}
      .title{font-size:20px;margin:2px 0 2px}
      .subtitle{font-size:12.5px;line-height:1.4}
      .grid,.cards,.split{grid-template-columns:1fr;gap:10px}
      .form-grid{grid-template-columns:1fr;gap:8px}
      .form-grid .btn{width:100%}
      .stack .btn{width:100%}
      .toast{left:12px;right:12px;max-width:none}
    }
  </style>
</head>
<body>
<div class="app"><aside class="side"><div class="brand"><div class="logo">⚡</div><div>Wingbuddy<br><span style="color:var(--muted);font-size:11px">Control Center</span></div></div><div class="nav" id="nav"></div><div class="side-foot"><div class="health"><strong id="sideHealth">Connecting…</strong><span id="sideHealthDetail">Runtime telemetry pending</span></div></div></aside><div><div class="mobile-nav" id="mobileNav"></div><main><div class="top"><div><div class="eyebrow">Adaptive AI Operations</div><div class="title">Wingbuddy Control Center</div><p class="subtitle">Live control plane for the Telegram assistant, adaptive model pool, autonomous execution, web research, memory, and runtime health.</p></div><div class="toolbar"><button class="btn" onclick="refreshAll()">↻ Refresh</button></div></div><div id="toast" class="toast"></div>
<section class="view active" id="view-overview"><div class="grid"><div class="card"><div class="label">Runtime</div><div class="value" id="overviewRuntime">—</div><div class="sub" id="overviewUptime">Uptime —</div></div><div class="card"><div class="label">Primary Model</div><div class="value" id="overviewModel">—</div><div class="sub" id="overviewPool">Model pool loading…</div></div><div class="card"><div class="label">Autonomous Execution</div><div class="value" id="overviewExec">—</div><div class="sub" id="overviewExecSub">Control-plane state</div></div><div class="card"><div class="label">Web Research</div><div class="value" id="overviewWeb">—</div><div class="sub" id="overviewWebSub">Evidence capability</div></div></div><div class="split"><div class="card section"><div class="section-head"><div><div class="section-title">Live Runtime Snapshot</div><div class="section-note">Derived from server telemetry.</div></div></div><div class="cards" id="runtimeCards"></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Adaptive Decision Surface</div><div class="section-note">Policy is observed here; safety limits stay backend-authoritative.</div></div></div><div class="stack" id="adaptiveCards"></div></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Recent Executions</div><div class="section-note" id="recentExecNote">Loading…</div></div><button class="btn" onclick="showView('executions')">Open Executions</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Execution</th><th>Status</th><th>Revision</th><th>Updated</th></tr></thead><tbody id="overviewExecTable"></tbody></table></div></div></section>
<section class="view" id="view-models"><div class="grid"><div class="card"><div class="label">Primary</div><div class="value" id="modelPrimary">—</div><div class="sub">Configuration-driven</div></div><div class="card"><div class="label">Fast Role</div><div class="value" id="modelFast">—</div><div class="sub">Preferred fast path</div></div><div class="card"><div class="label">Reasoning Role</div><div class="value" id="modelReasoning">—</div><div class="sub">Preferred reasoning path</div></div><div class="card"><div class="label">Embedding</div><div class="value" id="modelEmbedding">—</div><div class="sub">Configured embedding model</div></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Configured Model Pool</div><div class="section-note">Supplied by runtime configuration.</div></div></div><div class="cards" id="modelPoolCards"></div></div><div class="card section"><div class="section-head"><div><div class="section-title">API Key Health</div><div class="section-note" id="keyPoolNote">Loading…</div></div><button class="btn" onclick="loadKeys()">Refresh Keys</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Key</th><th>Status</th><th>Requests</th><th>Latency</th><th>Source</th></tr></thead><tbody id="keyTable"></tbody></table></div></div></section>
<section class="view" id="view-executions"><div class="grid"><div class="card"><div class="label">Engine</div><div class="value" id="execEngine">—</div><div class="sub" id="execEngineSub">—</div></div><div class="card"><div class="label">Active Leases</div><div class="value" id="execLeases">—</div><div class="sub">Distributed claim state</div></div><div class="card"><div class="label">Executions Started</div><div class="value" id="execStarted">—</div><div class="sub">Observed runtime metric</div></div><div class="card"><div class="label">Global Concurrency</div><div class="value" id="execConcurrency">—</div><div class="sub">Backend policy</div></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Execution Sessions</div><div class="section-note">Live persisted sessions and control actions.</div></div><button class="btn" onclick="loadExecutions()">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Graph</th><th>Status</th><th>Nodes</th><th>Revision</th><th>Updated</th><th>Actions</th></tr></thead><tbody id="execTable"></tbody></table></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Authoritative Tool Registry</div><div class="section-note">Tool policy metadata reported by the execution runtime.</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Tool</th><th>Policy</th><th>Capabilities</th><th>Description</th></tr></thead><tbody id="toolTable"></tbody></table></div></div></section>
<section class="view" id="view-research"><div class="grid"><div class="card"><div class="label">Provider</div><div class="value" id="webProvider">—</div><div class="sub" id="webConfigured">—</div></div><div class="card"><div class="label">Search</div><div class="value">Registry-backed</div><div class="sub">Execution decides the live tool path</div></div><div class="card"><div class="label">Evidence</div><div class="value">Source-first</div><div class="sub">Retrieved evidence → synthesis</div></div><div class="card"><div class="label">Attribution</div><div class="value">Telemetry</div><div class="sub">Inspect execution source path</div></div></div><div class="notice">Current-information tasks should use the configured live research capability. The dashboard does not fabricate research results.</div></section>
<section class="view" id="view-users"><div class="card section"><div class="section-head"><div><div class="section-title">Telegram User Context</div><div class="section-note">Changes are scoped to the selected Telegram user.</div></div><button class="btn" onclick="loadUsers()">Refresh Users</button></div><div class="form-grid"><select id="userSelect" class="select" onchange="onUserChange(this.value)"><option value="">Loading users…</option></select><input id="customUser" class="input" placeholder="Custom Telegram user ID" inputmode="numeric"/><button class="btn primary" onclick="applyCustomUser()">Target User</button></div><div class="notice" id="userHeadline" style="margin-top:9px">No user selected.</div></div><div class="split"><div class="card section"><div class="section-head"><div><div class="section-title">Long-Term Memory</div><div class="section-note" id="memoryMeta">Select a user.</div></div><button class="btn" onclick="loadMemories()">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Key</th><th>Category</th><th>Content</th><th>Action</th></tr></thead><tbody id="memoryTable"></tbody></table></div><div class="form-grid" style="margin-top:9px"><input id="memoryKey" class="input" placeholder="Memory key"/><input id="memoryContent" class="input" placeholder="Memory content"/><button class="btn" onclick="addMemory()">Store</button></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Personality & Mode</div><div class="section-note">Persistent user configuration.</div></div></div><div class="stack"><select id="personality" class="select"></select><select id="mode" class="select"></select><button class="btn primary" onclick="saveUserSettings()">Apply Settings</button></div></div></div></section>
<section class="view" id="view-reminders"><div class="card section"><div class="section-head"><div><div class="section-title">Reminder Queue</div><div class="section-note">Durable reminders backed by PostgreSQL.</div></div><button class="btn" onclick="loadReminders()">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Prompt</th><th>Due</th><th>Status</th><th>Snoozes</th><th>Actions</th></tr></thead><tbody id="reminderTable"></tbody></table></div><div class="form-grid" style="margin-top:9px"><input id="reminderPrompt" class="input" placeholder="Reminder prompt"/><input id="reminderMinutes" class="input" placeholder="Minutes from now" inputmode="numeric"/><button class="btn primary" onclick="addReminder()">Schedule</button></div></div></section>
<section class="view" id="view-runtime"><div class="card section"><div class="section-head"><div><div class="section-title">Runtime Configuration</div><div class="section-note">Safe, non-secret runtime state.</div></div><button class="btn" onclick="loadRuntimeConfig()">Refresh</button></div><div class="cards" id="runtimeConfigCards"></div></div><div class="card section"><div class="section-head"><div><div class="section-title">Environment State</div><div class="section-note">Secret values remain masked.</div></div><button class="btn" onclick="showEnvVars()">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Variable</th><th>Category</th><th>Status</th><th>Value</th></tr></thead><tbody id="envTable"></tbody></table></div></div></section>
</main></div></div>
<script>
const NAV=[['overview','Overview'],['models','AI Models'],['executions','Autonomous Execution'],['research','Web Research'],['users','Users & Memory'],['reminders','Reminders'],['runtime','Runtime']];
const state={runtime:null,telemetry:null,exec:null,users:[],userId:''};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function fmtUptime(s){if(!s)return '—';var h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?(h+'h '+m+'m'):m?(m+'m '+sec+'s'):(sec+'s')}
function toast(msg,bad){var t=$('toast');t.textContent=msg;t.style.display='block';t.style.borderColor=bad?'rgba(255,102,117,.4)':'#2a4665';clearTimeout(window._toast);window._toast=setTimeout(function(){t.style.display='none'},3500)}
function buildNav(){var a=$('nav'),b=$('mobileNav');NAV.forEach(function(item){var x=document.createElement('button');x.textContent=item[1];x.dataset.view=item[0];x.onclick=function(){showView(item[0])};a.appendChild(x);var y=x.cloneNode(true);y.onclick=function(){showView(item[0])};b.appendChild(y)})}
function showView(view){document.querySelectorAll('.view').forEach(function(x){x.classList.toggle('active',x.id==='view-'+view)});document.querySelectorAll('[data-view]').forEach(function(x){x.classList.toggle('active',x.dataset.view===view)});if(view==='models')loadKeys();if(view==='executions')loadExecutions();if(view==='research')loadRuntimeConfig();if(view==='users'){loadUsers();loadMemories();loadUserSettings()}if(view==='reminders')loadReminders();if(view==='runtime'){loadRuntimeConfig();showEnvVars()}}
async function api(path,options){var r=await fetch(path,options);var text=await r.text(),data={};try{data=text?JSON.parse(text):{}}catch(_){}if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data}
async function loadRuntimeConfig(){try{state.runtime=await api('/api/dashboard/runtime');renderRuntimeConfig()}catch(e){toast('Runtime config unavailable: '+e.message,true)}}
function renderRuntimeConfig(){var r=state.runtime||{},pool=r.modelPool||[];$('overviewModel').textContent=r.primaryModel||'—';$('overviewPool').textContent=pool.length?pool.join(' → '):'Pool not configured';$('modelPrimary').textContent=r.primaryModel||'—';$('modelFast').textContent=r.fastModel||'—';$('modelReasoning').textContent=r.reasoningModel||'—';$('modelEmbedding').textContent=r.embeddingModel||'—';$('webProvider').textContent=r.webResearchProvider||'—';$('webConfigured').textContent=r.webResearchConfigured?'Configured':'Not configured';$('overviewWeb').textContent=r.webResearchConfigured?'READY':'OFF';$('overviewWebSub').textContent=r.webResearchConfigured?'Configured research provider':'No live research credential configured';$('runtimeConfigCards').innerHTML=[['Primary model',r.primaryModel],['Fast role',r.fastModel],['Reasoning role',r.reasoningModel],['Extraction role',r.extractionModel],['Fallback models',(r.fallbackModels||[]).join(', ')||'—'],['Embedding model',r.embeddingModel],['Research provider',r.webResearchProvider||'—'],['Research credential',r.webResearchConfigured?'configured':'not configured'],['Execution flag',r.executionEngineEnabled?'enabled':'disabled'],['Bot runtime',r.telegramRuntimeActive?'active':'not initialized']].map(function(x){return '<div class="mini"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1]||'—')+'</span></div>'}).join('');$('modelPoolCards').innerHTML=pool.length?pool.map(function(m,i){return '<div class="mini"><strong>#'+(i+1)+' '+esc(m)+'</strong><span>'+(i===0?'Primary candidate':'Configured fallback candidate')+'</span></div>'}).join(''):'<div class="empty">No configured model pool.</div>'}
async function loadTelemetry(){try{state.telemetry=await api('/api/dashboard/telemetry');renderTelemetry()}catch(e){toast('Telemetry unavailable: '+e.message,true)}}
function renderTelemetry(){var d=state.telemetry||{};$('overviewRuntime').textContent='HEALTHY';$('overviewUptime').textContent='Uptime '+fmtUptime(d.uptimeSeconds);$('sideHealth').textContent='Runtime telemetry live';$('sideHealthDetail').textContent='CPU '+(d.system&&d.system.cpuCores||'—')+' cores • RAM '+(d.system&&d.system.heapUsedMb||'—')+' MB';var arr=[['CPU cores',d.system&&d.system.cpuCores],['Heap',(d.system&&d.system.heapUsedMb||'—')+' / '+(d.system&&d.system.heapTotalMb||'—')+' MB'],['RSS',(d.system&&d.system.rssMb||'—')+' MB'],['Memory pressure',d.system&&d.system.memoryPressureRatio!=null?Math.round(d.system.memoryPressureRatio*100)+'%':'—'],['DB pool max',d.pool&&d.pool.adaptiveMaxConnections],['Connection timeout',d.pool&&d.pool.adaptiveConnectionTimeoutMs?d.pool.adaptiveConnectionTimeoutMs+' ms':'—'],['Cache TTL',d.cache&&d.cache.adaptiveCurrentTtlMs?Math.round(d.cache.adaptiveCurrentTtlMs/1000)+'s':'—'],['pgvector',d.pool&&d.pool.pgVectorEnabled?'available':'unavailable'],['Users',d.counts&&d.counts.users],['Memories',d.counts&&d.counts.memories],['Reminders',d.counts&&d.counts.reminders],['Messages',d.counts&&d.counts.messages]];$('runtimeCards').innerHTML=arr.map(function(x){return '<div class="mini"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1]==null?'—':x[1])+'</span></div>'}).join('');var adaptive=[['Memory policy','relevance-aware retrieval'],['Execution policy','adaptive limits with hard safety ceilings'],['Model routing','configuration-driven candidate pool'],['Web research','provider-backed evidence retrieval'],['Persistence','PostgreSQL authoritative state'],['Execution safety','distributed leases + idempotency']];$('adaptiveCards').innerHTML=adaptive.map(function(x){return '<div class="mini"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1])+'</span></div>'}).join('')}
async function loadExecutions(){try{state.exec=await api('/api/execution/health');var s=await api('/api/execution/sessions?limit=20'),a=state.exec.autonomousExecution||{},cfg=a.config||{},met=a.metrics||{},rows=s.sessions||[];$('overviewExec').textContent=a.enabled?'ON':'OFF';$('overviewExecSub').textContent=a.enabled?'Planner + compiler + execution active':'Autonomous execution disabled';$('execEngine').textContent=a.enabled?'ON':'OFF';$('execEngineSub').textContent=a.enabled?'Planner + compiler + execution active':'Conversational pass-through';$('execLeases').textContent=met.activeLeasesCount==null?'—':met.activeLeasesCount;$('execStarted').textContent=met.totalExecutionsStarted==null?'—':met.totalExecutionsStarted;$('execConcurrency').textContent=cfg.maxConcurrency==null?'—':cfg.maxConcurrency;$('recentExecNote').textContent=rows.length+' recent sessions';$('overviewExecTable').innerHTML=rows.slice(0,6).map(function(r){return '<tr><td><span class="mono">'+esc(r.graphId)+'</span></td><td>'+statusPill(r.status)+'</td><td>r'+esc(r.planRevision)+'</td><td>'+esc(localTime(r.updatedAt||r.startedAt))+'</td></tr>'}).join('')||'<tr><td colspan="4" class="empty">No executions recorded.</td></tr>';$('execTable').innerHTML=rows.map(renderExecRow).join('')||'<tr><td colspan="6" class="empty">No execution sessions recorded.</td></tr>';var tools=a.tools||[];$('toolTable').innerHTML=tools.map(function(t){var p=t.policy||{};return '<tr><td class="mono">'+esc(t.name)+'</td><td>'+policyPill(p)+'</td><td>'+esc((t.requiredCapabilities||p.requiredCapabilities||[]).join(', ')||'—')+'</td><td>'+esc(p.description||'')+'</td></tr>'}).join('')||'<tr><td colspan="4" class="empty">No registered tools reported.</td></tr>'}catch(e){toast('Execution telemetry unavailable: '+e.message,true)}}
function localTime(x){try{return new Date(x).toLocaleString()}catch(_){return '—'}}
function statusPill(s){var v=String(s||'unknown'),c=v==='completed'?'good':(v==='failed'||v==='cancelled'?'bad':(v.indexOf('approval')>=0||v==='paused'?'warn':''));return '<span class="pill '+c+'">'+esc(v)+'</span>'}
function policyPill(p){if(p.isDestructive)return '<span class="pill bad">destructive</span>';if(p.requiresApproval)return '<span class="pill warn">approval required</span>';if(p.isMutating)return '<span class="pill">guarded mutation</span>';return '<span class="pill good">read / idempotent</span>'}
function nodeCount(s){var a=[].concat(s.completedNodes||[],s.currentNodes||[],s.waitingApprovalNodes||[],s.failedNodes||[]);return a.length||'—'}
function renderExecRow(s){var actions='';if(s.status==='paused_for_approval'&&(s.waitingApprovalNodes||[]).length){var n=s.waitingApprovalNodes[0];actions='<button class="btn" onclick="approveNode(\''+esc(s.graphId)+'\','+Number(s.planRevision)+',\''+esc(n)+'\',true)">Approve</button> <button class="btn danger" onclick="approveNode(\''+esc(s.graphId)+'\','+Number(s.planRevision)+',\''+esc(n)+'\',false)">Deny</button>'}else if(s.status==='executing'){actions='<button class="btn" onclick="pauseExec(\''+esc(s.graphId)+'\','+Number(s.planRevision)+')">Pause</button> <button class="btn danger" onclick="cancelExec(\''+esc(s.graphId)+'\','+Number(s.planRevision)+')">Cancel</button>'}else if(s.status==='paused'){actions='<button class="btn" onclick="resumeExec(\''+esc(s.graphId)+'\','+Number(s.planRevision)+')">Resume</button>'}return '<tr><td><div class="mono">'+esc(s.graphId)+'</div><div class="section-note">'+esc(String(s.executionId||'').slice(0,18))+'</div></td><td>'+statusPill(s.status)+'</td><td>'+nodeCount(s)+'</td><td>r'+esc(s.planRevision)+'</td><td>'+esc(localTime(s.updatedAt||s.startedAt))+'</td><td>'+actions+'</td></tr>'}
async function approveNode(graphId,planRevision,nodeId,approved){try{await api('/api/execution/approval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graphId:graphId,planRevision:planRevision,nodeId:nodeId,approved:approved,telegramUserId:Number(state.userId)||1})});toast(approved?'Node approved':'Node denied');loadExecutions()}catch(e){toast(e.message,true)}}
async function pauseExec(graphId,planRevision){try{await api('/api/execution/pause',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graphId:graphId,planRevision:planRevision,reason:'Paused via Wingbuddy Control Center'})});toast('Execution paused');loadExecutions()}catch(e){toast(e.message,true)}}
async function resumeExec(graphId,planRevision){try{await api('/api/execution/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graphId:graphId,planRevision:planRevision,telegramUserId:Number(state.userId)||1})});toast('Execution resumed');loadExecutions()}catch(e){toast(e.message,true)}}
async function cancelExec(graphId,planRevision){if(!confirm('Cancel this execution?'))return;try{await api('/api/execution/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graphId:graphId,planRevision:planRevision,reason:'Cancelled via Wingbuddy Control Center'})});toast('Execution cancelled');loadExecutions()}catch(e){toast(e.message,true)}}
async function loadKeys(){try{var d=await api('/api/keys');$('keyPoolNote').textContent=(d.healthyKeys||0)+'/'+(d.totalKeys||0)+' healthy • '+(d.rotationMode||'unknown')+' rotation';$('keyTable').innerHTML=(d.keys||[]).map(function(k){var status=k.status==='healthy'?'<span class="status"><span class="dot green"></span>Healthy</span>':k.status==='cooldown'?'<span class="pill warn">Cooldown '+esc(k.cooldownSecondsLeft)+'s</span>':'<span class="pill bad">'+esc(k.status)+'</span>';return '<tr><td><strong>'+esc(k.name)+'</strong></td><td>'+status+'</td><td>'+esc(k.totalSuccess||0)+' success / '+esc(k.totalErrors||0)+' errors</td><td>'+esc(k.avgLatencyMs||'—')+' ms</td><td>'+esc(k.source||'—')+'</td></tr>'}).join('')||'<tr><td colspan="5" class="empty">No API keys reported.</td></tr>'}catch(e){toast('Key pool unavailable: '+e.message,true)}}
async function loadUsers(){try{var d=await api('/api/dashboard/users');state.users=d.users||[];var s=$('userSelect');s.innerHTML=state.users.length?state.users.map(function(u){return '<option value="'+esc(u.telegramUserId)+'">'+esc(u.firstName||'User')+' '+(u.username?'(@'+esc(u.username)+') ':'')+'['+esc(u.telegramUserId)+']</option>'}).join(''):'<option value="">No registered users</option>';if(!state.userId&&state.users.length)state.userId=String(state.users[0].telegramUserId);if(state.userId)s.value=state.userId;renderUserHeadline();loadUserSettings();loadMemories();loadReminders()}catch(e){toast('Users unavailable: '+e.message,true)}}
function onUserChange(id){if(!id)return;state.userId=String(id);renderUserHeadline();loadUserSettings();loadMemories();loadReminders()}
function applyCustomUser(){var id=$('customUser').value.trim();if(!/^\\d+$/.test(id)){toast('Enter a numeric Telegram user ID',true);return}state.userId=id;renderUserHeadline();loadUserSettings();loadMemories();loadReminders()}
function renderUserHeadline(){var u=state.users.find(function(x){return String(x.telegramUserId)===String(state.userId)});$('userHeadline').textContent=u?((u.firstName||'User')+(u.username?' (@'+u.username+')':'')+' — Telegram ID '+u.telegramUserId):(state.userId?'Custom Telegram user — '+state.userId:'No user selected')}
function fillSelect(id,items,current){var s=$(id);s.innerHTML=items.map(function(x){return '<option value="'+esc(x.value)+'" '+(x.value===current?'selected':'')+'>'+esc(x.label)+'</option>'}).join('')}
async function loadUserSettings(){if(!state.userId)return;try{var d=await api('/api/dashboard/user-settings?userId='+encodeURIComponent(state.userId));fillSelect('personality',[['playful','Playful'],['concise','Concise'],['analytical','Analytical'],['empathetic','Empathetic'],['creative','Creative'],['professional','Professional']].map(function(x){return {value:x[0],label:x[1]}}),d.personality||'playful');fillSelect('mode',[['general','General'],['study','Study'],['coder','Coder'],['deep_research','Deep Research'],['math','Math'],['creative','Creative'],['auto','Auto']].map(function(x){return {value:x[0],label:x[1]}}),d.mode||'general')}catch(e){toast('User settings unavailable: '+e.message,true)}}
async function saveUserSettings(){if(!state.userId){toast('Select a user first',true);return}try{var d=await api('/api/dashboard/user-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(state.userId),personality:$('personality').value,mode:$('mode').value})});toast('Settings saved: '+d.personality+' / '+d.mode)}catch(e){toast(e.message,true)}}
async function loadMemories(){if(!state.userId)return;try{var d=await api('/api/dashboard/memories?userId='+encodeURIComponent(state.userId));$('memoryMeta').textContent=(d.memories||[]).length+' stored memories • pgvector '+(d.pgVectorAvailable?'available':'unavailable');$('memoryTable').innerHTML=(d.memories||[]).map(function(m){return '<tr><td class="mono">'+esc(m.key)+'</td><td>'+esc(m.category)+'</td><td>'+esc(m.content)+'</td><td><button class="btn danger" onclick="deleteMemory(\''+esc(m.key)+'\')">Delete</button></td></tr>'}).join('')||'<tr><td colspan="4" class="empty">No memories for this user.</td></tr>'}catch(e){toast('Memory unavailable: '+e.message,true)}}
async function addMemory(){if(!state.userId){toast('Select a user first',true);return}var key=$('memoryKey').value.trim(),content=$('memoryContent').value.trim();if(!key||!content){toast('Key and content are required',true);return}try{await api('/api/dashboard/memories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(state.userId),key:key,content:content,category:'fact'})});$('memoryKey').value='';$('memoryContent').value='';toast('Memory stored');loadMemories()}catch(e){toast(e.message,true)}}
async function deleteMemory(key){if(!confirm('Delete this memory?'))return;try{await api('/api/dashboard/memories/'+encodeURIComponent(key)+'?userId='+encodeURIComponent(state.userId),{method:'DELETE'});loadMemories();toast('Memory deleted')}catch(e){toast(e.message,true)}}
async function loadReminders(){if(!state.userId)return;try{var d=await api('/api/dashboard/reminders?userId='+encodeURIComponent(state.userId));$('reminderTable').innerHTML=(d.reminders||[]).map(function(r){var due=new Date(r.dueAt),status=r.isCompleted?'<span class="pill">completed</span>':due<=new Date()?'<span class="pill warn">due</span>':'<span class="pill good">scheduled</span>';return '<tr><td>'+esc(r.prompt)+'</td><td>'+esc(due.toLocaleString())+'</td><td>'+status+'</td><td>'+esc(r.snoozeCount||0)+'</td><td>'+(r.isCompleted?'—':'<button class="btn" onclick="completeReminder('+r.id+')">Done</button> <button class="btn" onclick="snoozeReminder('+r.id+')">+10m</button> ')+'<button class="btn danger" onclick="deleteReminder('+r.id+')">Delete</button></td></tr>'}).join('')||'<tr><td colspan="5" class="empty">No reminders for this user.</td></tr>'}catch(e){toast('Reminder queue unavailable: '+e.message,true)}}
async function addReminder(){if(!state.userId){toast('Select a user first',true);return}var prompt=$('reminderPrompt').value.trim(),minutes=Number($('reminderMinutes').value.trim())||15;if(!prompt){toast('Reminder prompt is required',true);return}try{await api('/api/dashboard/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(state.userId),prompt:prompt,dueInMinutes:minutes})});$('reminderPrompt').value='';$('reminderMinutes').value='';toast('Reminder scheduled');loadReminders()}catch(e){toast(e.message,true)}}
async function completeReminder(id){try{await api('/api/dashboard/reminders/'+id+'/complete',{method:'PATCH'});loadReminders();toast('Reminder completed')}catch(e){toast(e.message,true)}}
async function snoozeReminder(id){try{await api('/api/dashboard/reminders/'+id+'/snooze',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({minutes:10})});loadReminders();toast('Reminder snoozed')}catch(e){toast(e.message,true)}}
async function deleteReminder(id){if(!confirm('Delete this reminder?'))return;try{await api('/api/dashboard/reminders/'+id,{method:'DELETE'});loadReminders();toast('Reminder deleted')}catch(e){toast(e.message,true)}}
async function showEnvVars(){try{var d=await api('/api/env');$('envTable').innerHTML=(d.variables||[]).map(function(v){return '<tr><td class="mono">'+esc(v.key)+'</td><td>'+esc(v.category)+'</td><td>'+ (v.isSet?'<span class="pill good">configured</span>':'<span class="pill warn">unset</span>')+'</td><td>'+ (v.isSensitive?'••••••••':esc(v.value||''))+'</td></tr>'}).join('')||'<tr><td colspan="4" class="empty">No environment variables reported.</td></tr>'}catch(e){toast('Environment manager unavailable: '+e.message,true)}}
async function refreshAll(){await Promise.allSettled([loadRuntimeConfig(),loadTelemetry(),loadExecutions(),loadKeys(),loadUsers()]);toast('Dashboard refreshed')}
window.loadRuntimeConfig = loadRuntimeConfig;
buildNav();refreshAll();setInterval(loadTelemetry,5000);setInterval(loadExecutions,5000);setInterval(loadRuntimeConfig,10000);setInterval(function(){if(state.userId){loadMemories();loadReminders()}},12000);
</script>
</body>
</html>`;
}
