export function renderDashboardAIRoutingControls(): string {
  return `
<section id="ai-routing-control-plane" style="margin:24px 0;padding:20px;border:1px solid var(--line);border-radius:18px;background:var(--panel);color:var(--text);font-family:system-ui,sans-serif">
  <div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap">
    <div><h2 style="margin:0 0 6px;font-size:20px">AI Control Plane</h2><p style="margin:0;color:var(--muted);font-size:13px">Provider, model, routing policy, health and observability controls backed by PostgreSQL.</p></div>
    <div style="display:flex;gap:8px;align-items:center"><label style="font-size:12px;color:var(--muted)">Auto refresh <input id="air-auto" type="checkbox" checked style="vertical-align:middle;margin-left:5px"></label><button id="air-refresh" style="padding:9px 13px;border:1px solid var(--line);border-radius:10px;background:var(--panel-2);color:var(--text);cursor:pointer">Refresh</button></div>
  </div>
  <div id="air-status" style="margin-top:12px;font-size:13px;color:var(--muted)"></div>
  <div id="air-summary" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px;margin-top:14px"></div>
  <div id="air-providers" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px;margin-top:16px"></div>

  <div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:18px">
    <div style="flex:1 1 650px;min-width:0"><h3 style="font-size:15px;margin:0 0 10px">Registered models</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:8px">Provider</th><th style="text-align:left;padding:8px">Model</th><th style="padding:8px">State</th><th style="padding:8px">Action</th></tr></thead><tbody id="air-models"></tbody></table></div></div>
    <div style="flex:0 1 320px"><h3 style="font-size:15px;margin:0 0 10px">Register model</h3><div style="display:grid;gap:8px"><select id="air-provider" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"><option value="gemini">Gemini</option><option value="groq">Groq</option><option value="mistral">Mistral</option></select><input id="air-model-id" placeholder="Provider model ID" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-model-name" placeholder="Display name (optional)" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-model-capabilities" placeholder="Capabilities, comma separated" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><button id="air-add-model" style="padding:10px;border:0;border-radius:10px;background:var(--primary);color:var(--on-primary);cursor:pointer">Register model</button></div></div>
  </div>

  <div style="margin-top:18px"><h3 style="font-size:15px;margin:0 0 10px">Adaptive routing policy</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px"><div style="padding:9px;border-radius:9px;background:var(--panel-3);border:1px solid var(--line);color:var(--success);font-size:13px">Adaptive · provider-neutral</div><input id="air-cap" type="number" min="0" max="100" placeholder="Capability weight" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-health-weight" type="number" min="0" max="100" placeholder="Health weight" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-latency" type="number" min="0" max="100" placeholder="Latency weight" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-priority" type="number" min="0" max="100" placeholder="Priority weight" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="air-attempts" type="number" min="1" max="6" placeholder="Max attempts" style="padding:9px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><button id="air-save-policy" style="padding:10px;border:0;border-radius:10px;background:var(--success);color:var(--on-primary);cursor:pointer">Save policy</button></div><div style="margin-top:8px;font-size:11px;color:var(--muted)">Every enabled, compatible registered model participates on equal provider footing. Capability match, health, latency and configured priority determine the score. Legacy primary metadata is compatibility-only.</div></div>

  <div style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h3 style="font-size:15px;margin:0 0 10px">Health & observability</h3><button id="air-reset-health" style="padding:7px 10px;border:1px solid var(--danger-border);border-radius:8px;background:var(--danger-bg);color:var(--danger);cursor:pointer">Reset all health</button></div><div id="air-health"></div></div>
</section>
<script>
(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function json(url, options) { const r = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); const body = await r.json(); if(!r.ok) throw new Error(body.error || 'Request failed'); return body; }
  const card = (label, value) => '<div style="padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--panel-2)"><div style="font-size:11px;color:var(--muted)">'+esc(label)+'</div><div style="margin-top:4px;font-weight:700;font-size:18px">'+esc(value)+'</div></div>';
  async function load() {
    $('air-status').textContent = 'Refreshing AI control plane…';
    try {
      const [providers, models, policy, health, obs] = await Promise.all([json('/api/providers'), json('/api/models'), json('/api/ai/routing/policy'), json('/api/ai/routing/health'), json('/api/ai/observability')]);
      const totals = obs.observability.totals;
      $('air-summary').innerHTML = [card('Routing', 'Adaptive'), card('Requests', totals.requests), card('Success rate', totals.successRate+'%'), card('Avg latency', totals.avgLatencyMs+' ms'), card('Models', models.models.length), card('Ready providers', providers.providers.filter(p=>p.enabled&&p.configured&&p.adapterAvailable).length)].join('');
      $('air-providers').innerHTML = providers.providers.map(p => '<div style="padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel-2)"><div style="font-weight:700">'+esc(p.name)+'</div><div style="font-size:12px;color:var(--muted);margin-top:3px">'+esc(p.id)+' · '+(p.adapterAvailable?'adapter ready':'adapter missing')+'</div><div style="margin-top:7px"><span class="air-provider-state" data-ready="'+String(Boolean(p.enabled&&p.configured))+'">● '+(p.enabled&&p.configured?'Ready':'Not ready')+'</span></div><div style="margin-top:7px"><button data-provider="'+esc(p.id)+'" class="air-toggle" style="padding:6px 9px;border-radius:8px;border:1px solid var(--line);background:var(--panel-3);color:var(--text);cursor:pointer">'+(p.enabled?'Disable':'Enable')+'</button><button data-test-provider="'+esc(p.id)+'" style="padding:6px 9px;margin-left:6px;border-radius:8px;border:1px solid var(--line);background:var(--panel-3);color:var(--text);cursor:pointer">Test</button></div></div>').join('');
      $('air-models').innerHTML = models.models.length ? models.models.map(m => '<tr style="border-top:1px solid var(--line)"><td style="padding:8px">'+esc(m.provider)+'</td><td style="padding:8px"><div>'+esc(m.name)+'</div><div style="font-size:11px;color:var(--muted)">'+esc(m.modelId)+'</div></td><td style="padding:8px;text-align:center">'+(m.enabled?'✓':'—')+'</td><td style="padding:8px;text-align:center"><button class="air-model-toggle" data-id="'+esc(m.id)+'" data-enabled="'+String(m.enabled)+'" style="padding:6px 8px;border-radius:8px;border:1px solid var(--line);background:var(--panel-3);color:var(--text);cursor:pointer">'+(m.enabled?'Disable':'Enable')+'</button></td></tr>').join('') : '<tr><td colspan="4" style="padding:12px;color:var(--muted)">No registered models yet.</td></tr>';
      $('air-cap').value = policy.policy.capabilityWeight; $('air-health-weight').value = policy.policy.healthWeight; $('air-latency').value = policy.policy.latencyWeight; $('air-priority').value = policy.policy.priorityWeight; $('air-attempts').value = policy.policy.maxAttempts;
      const hm = new Map(health.health.map(h=>[h.id,h]));
      $('air-health').innerHTML = '<div style="overflow:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th style="text-align:left;padding:8px">Model</th><th style="padding:8px">Health</th><th style="padding:8px">Latency</th><th style="padding:8px">Success/Fail</th><th style="text-align:left;padding:8px">Last error</th><th style="padding:8px">Action</th></tr></thead><tbody>'+health.health.map(h => '<tr style="border-top:1px solid var(--line)"><td style="padding:8px">'+esc(h.provider+'/'+h.modelId)+'</td><td style="padding:8px;text-align:center">'+esc(h.healthScore)+'</td><td style="padding:8px;text-align:center">'+esc(h.ewmaLatencyMs)+' ms</td><td style="padding:8px;text-align:center">'+esc(h.successes)+' / '+esc(h.failures)+'</td><td style="padding:8px;max-width:300px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(h.lastError||'—')+'</td><td style="padding:8px;text-align:center"><button class="air-reset-model" data-id="'+esc(h.id)+'" style="padding:6px 8px;border-radius:8px;border:1px solid var(--line);background:var(--panel-3);color:var(--text);cursor:pointer">Reset</button></td></tr>').join('')+'</tbody></table></div>';
      document.querySelectorAll('#air-routing-control-plane .air-provider-state').forEach(el=>el.style.color=el.dataset.ready==='true'?'var(--success)':'var(--warning)');
      $('air-status').textContent = 'Routing: Adaptive · provider-neutral · Observability since '+new Date(obs.observability.windowStartedAt).toLocaleString();
      document.querySelectorAll('.air-toggle').forEach(b => b.onclick = async () => { const p = providers.providers.find(x=>x.id===b.dataset.provider); await json('/api/providers/'+encodeURIComponent(b.dataset.provider),{method:'PATCH',body:JSON.stringify({enabled:!p.enabled})}); load(); });
      document.querySelectorAll('[data-test-provider]').forEach(b => b.onclick = async () => {
        const p = providers.providers.find(x => x.id === b.dataset.testProvider);
        if (!p) return;
        const requiresChatModel = (p.capabilities || []).includes('chat');
        const m = models.models.find(x => x.provider === p.id && x.enabled);
        if (requiresChatModel && !m) return alert('Enable or register a model for this provider first.');
        const result = await json('/api/providers/' + encodeURIComponent(p.id) + '/test', {
          method: 'POST',
          body: JSON.stringify({ model: m ? m.modelId : '' })
        });
        alert(result.ok ? 'Provider test passed in ' + result.latencyMs + 'ms' : ('Provider test failed: ' + result.error));
      });
      document.querySelectorAll('.air-model-toggle').forEach(b => b.onclick = async () => { await json('/api/models/'+encodeURIComponent(b.dataset.id),{method:'PATCH',body:JSON.stringify({enabled:b.dataset.enabled!=='true'})}); load(); });
      document.querySelectorAll('.air-reset-model').forEach(b => b.onclick = async () => { await json('/api/ai/health/reset',{method:'POST',body:JSON.stringify({modelId:hm.get(b.dataset.id)?.modelId,provider:hm.get(b.dataset.id)?.provider})}); load(); });
    } catch(e) { $('air-status').textContent = 'Error: '+(e?.message||String(e)); }
  }
  $('air-refresh').onclick = load;
  $('air-add-model').onclick = async () => { try { await json('/api/models',{method:'POST',body:JSON.stringify({provider:$('air-provider').value,modelId:$('air-model-id').value,name:$('air-model-name').value,capabilities:$('air-model-capabilities').value.split(',').map(x=>x.trim()).filter(Boolean)})}); $('air-model-id').value=''; $('air-model-name').value=''; load(); } catch(e){ alert(e.message); } };
  $('air-save-policy').onclick = async () => { try { await json('/api/ai/routing/policy',{method:'PATCH',body:JSON.stringify({strategy:'adaptive',capabilityWeight:Number($('air-cap').value),healthWeight:Number($('air-health-weight').value),latencyWeight:Number($('air-latency').value),priorityWeight:Number($('air-priority').value),maxAttempts:Number($('air-attempts').value)})}); load(); } catch(e){alert(e.message);} };
  $('air-reset-health').onclick = async () => { if(!confirm('Reset all adaptive health and observability counters?')) return; try { await json('/api/ai/health/reset',{method:'POST',body:'{}'}); load(); } catch(e){alert(e.message);} };
  let timer = setInterval(()=> { if($('air-auto')?.checked) load(); }, 15000);
  window.addEventListener('beforeunload',()=>clearInterval(timer));
  load();
})();
</script>`;
}
