export function renderDashboardWebResearchControlPlane(): string {
  return [
    '<style>',
    '.wb-research-container { display: flex; flex-direction: column; gap: 16px; margin-top: 14px; }',
    '.wb-research-grid-2col { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }',
    '.wb-research-card { background: var(--panel-2, #0d1a2d); border: 1px solid var(--line, #1c2e4a); border-radius: 12px; padding: 16px; }',
    '.wb-research-section-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; flex-wrap: wrap; gap: 8px; }',
    '.wb-research-metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 8px; margin-bottom: 14px; }',
    '.wb-research-metric-card { background: var(--panel-3, #091322); border: 1px solid var(--line, #1c2e4a); border-radius: 8px; padding: 10px 12px; }',
    '.wb-research-metric-val { font-size: 18px; font-weight: 700; color: var(--text, #e2e8f0); }',
    '.wb-research-metric-lbl { font-size: 11px; color: var(--muted, #8da2c0); margin-top: 2px; }',
    '.wb-research-trace-step { display: flex; gap: 12px; padding: 10px 12px; border-left: 2px solid #3b82f6; background: var(--panel-3, #091322); border-radius: 0 8px 8px 0; margin-bottom: 8px; font-size: 12px; }',
    '.wb-research-result-item { background: var(--panel-3, #091322); border: 1px solid var(--line, #1c2e4a); border-radius: 8px; padding: 12px; margin-bottom: 10px; }',
    '.wb-research-result-title { font-size: 14px; font-weight: 600; color: #60a5fa; text-decoration: none; display: inline-block; margin-bottom: 4px; }',
    '.wb-research-result-title:hover { text-decoration: underline; }',
    '.wb-research-result-url { font-size: 11px; color: #94a3b8; word-break: break-all; margin-bottom: 6px; font-family: ui-monospace, monospace; }',
    '.wb-research-result-snippet { font-size: 12px; color: var(--text, #cbd5e1); line-height: 1.5; }',
    '.wb-research-keys-list { display: flex; flex-direction: column; gap: 8px; }',
    '.wb-research-key-row { display: flex; justify-content: space-between; align-items: center; padding: 8px 12px; background: var(--panel-3, #091322); border: 1px solid var(--line, #1c2e4a); border-radius: 8px; font-size: 12px; flex-wrap: wrap; gap: 6px; }',
    '@media (max-width: 900px) { .wb-research-grid-2col { grid-template-columns: 1fr; } }',
    '</style>',
    '<script>',
    '(() => {',
    '  function mountResearchControlPlane() {',
    '    const researchView = document.getElementById("view-research");',
    '    if (!researchView || document.getElementById("wb-research-control-plane")) return;',
    '    const wrap = document.createElement("div");',
    '    wrap.id = "wb-research-control-plane";',
    '    wrap.className = "wb-research-container";',
    '    wrap.innerHTML = \'<div class="wb-research-card">\' +',
    '      \'<div class="wb-research-section-head">\' +',
    '        \'<div>\' +',
    '          \'<div class="section-title">Research Runtime & Telemetry</div>\' +',
    '          \'<div class="section-note">Authoritative execution measurements, live key pool health, and cache performance.</div>\' +',
    '        \'</div>\' +',
    '        \'<button class="btn" id="wb-res-refresh-telemetry">↻ Refresh Telemetry</button>\' +',
    '      \'</div>\' +',
    '      \'<div class="wb-research-metrics-grid">\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-req-today">0</div><div class="wb-research-metric-lbl">Requests Today</div></div>\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-success-rate">100%</div><div class="wb-research-metric-lbl">Success Rate</div></div>\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-cache-hits">0</div><div class="wb-research-metric-lbl">Cache Hits (<span id="wb-res-cache-rate">0%</span>)</div></div>\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-avg-lat">0ms</div><div class="wb-research-metric-lbl">Avg Latency</div></div>\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-p95-lat">0ms</div><div class="wb-research-metric-lbl">p95 Latency</div></div>\' +',
    '        \'<div class="wb-research-metric-card"><div class="wb-research-metric-val" id="wb-res-provider-status">—</div><div class="wb-research-metric-lbl">Tavily Status</div></div>\' +',
    '      \'</div>\' +',
    '    \'</div>\' +',
    '    \'<div class="wb-research-card">\' +',
    '      \'<div class="wb-research-section-head">\' +',
    '        \'<div>\' +',
    '          \'<div class="section-title">Tavily API Key Pool & Encryption</div>\' +',
    '          \'<div class="section-note">Add and manage multiple Tavily API keys with test-before-save, AES-256 encryption, and auto-failover.</div>\' +',
    '        \'</div>\' +',
    '        \'<div style="display:flex;gap:8px;align-items:center;">\' +',
    '          \'<select id="wb-tavily-rotation-mode" class="select" style="width:auto">\' +',
    '            \'<option value="round_robin">Round Robin</option>\' +',
    '            \'<option value="failover">Failover</option>\' +',
    '          \'</select>\' +',
    '          \'<button class="btn" id="wb-tavily-save-rotation">Save Mode</button>\' +',
    '        \'</div>\' +',
    '      \'</div>\' +',
    '      \'<div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px;">\' +',
    '        \'<input id="wb-tavily-new-key" class="input" type="password" placeholder="Enter Tavily API key (tvly-...)" style="flex:1;min-width:220px;" autocomplete="off"/>\' +',
    '        \'<input id="wb-tavily-new-name" class="input" type="text" placeholder="Key Label (e.g. Primary Tavily Key)" style="width:200px;"/>\' +',
    '        \'<button id="wb-tavily-test-btn" class="btn">⚡ Test Key</button>\' +',
    '        \'<button id="wb-tavily-add-btn" class="btn primary">＋ Save Key</button>\' +',
    '      \'</div>\' +',
    '      \'<div id="wb-tavily-key-test-result" style="font-size:12px;margin-bottom:10px;display:none;"></div>\' +',
    '      \'<div class="wb-research-keys-list" id="wb-tavily-keys-list">\' +',
    '        \'<div class="empty">Loading Tavily key pool...</div>\' +',
    '      \'</div>\' +',
    '    \'</div>\' +',
    '    \'<div class="wb-research-grid-2col">\' +',
    '      \'<div class="wb-research-card">\' +',
    '        \'<div class="wb-research-section-head">\' +',
    '          \'<div>\' +',
    '            \'<div class="section-title">Research Sandbox & Query Runner</div>\' +',
    '            \'<div class="section-note">Execute live web searches through the production Tavily service.</div>\' +',
    '          \'</div>\' +',
    '        \'</div>\' +',
    '        \'<div style="display:flex;flex-direction:column;gap:10px;">\' +',
    '          \'<div>\' +',
    '            \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Search Query</label>\' +',
    '            \'<textarea id="wb-res-query" class="input" rows="3" placeholder="e.g., Latest breakthroughs in solid-state batteries 2026" style="resize:vertical;"></textarea>\' +',
    '          \'</div>\' +',
    '          \'<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">\' +',
    '            \'<div>\' +',
    '              \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Depth</label>\' +',
    '              \'<select id="wb-res-depth" class="select"><option value="basic">Basic (Fast)</option><option value="advanced">Advanced (Deep Search)</option></select>\' +',
    '            \'</div>\' +',
    '            \'<div>\' +',
    '              \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Topic</label>\' +',
    '              \'<select id="wb-res-topic" class="select"><option value="general">General</option><option value="news">News</option><option value="finance">Finance</option></select>\' +',
    '            \'</div>\' +',
    '          \'</div>\' +',
    '          \'<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">\' +',
    '            \'<div>\' +',
    '              \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Max Results</label>\' +',
    '              \'<input id="wb-res-max-results" class="input" type="number" min="1" max="20" value="5" />\' +',
    '            \'</div>\' +',
    '            \'<div>\' +',
    '              \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Time Range</label>\' +',
    '              \'<select id="wb-res-timerange" class="select"><option value="">Any Time</option><option value="day">Past Day</option><option value="week">Past Week</option><option value="month">Past Month</option><option value="year">Past Year</option></select>\' +',
    '            \'</div>\' +',
    '          \'</div>\' +',
    '          \'<div>\' +',
    '            \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Include Domains (comma-separated)</label>\' +',
    '            \'<input id="wb-res-inc-domains" class="input" placeholder="e.g. arxiv.org, nature.com, github.com" />\' +',
    '          \'</div>\' +',
    '          \'<div>\' +',
    '            \'<label style="font-size:12px;color:var(--muted);display:block;margin-bottom:4px;">Exclude Domains (comma-separated)</label>\' +',
    '            \'<input id="wb-res-exc-domains" class="input" placeholder="e.g. pinterest.com, quora.com" />\' +',
    '          \'</div>\' +',
    '          \'<button id="wb-res-run-search" class="btn primary" style="margin-top:6px;">🔍 Run Live Search</button>\' +',
    '        \'</div>\' +',
    '        \'<hr style="border:0;border-top:1px solid var(--line);margin:16px 0;" />\' +',
    '        \'<div class="wb-research-section-head">\' +',
    '          \'<div>\' +',
    '            \'<div class="section-title">Production URL Extractor</div>\' +',
    '            \'<div class="section-note">Extract raw content directly from specific web URLs.</div>\' +',
    '          \'</div>\' +',
    '        \'</div>\' +',
    '        \'<div style="display:flex;flex-direction:column;gap:10px;">\' +',
    '          \'<textarea id="wb-res-extract-urls" class="input" rows="2" placeholder="https://example.com/article, https://news.ycombinator.com" style="resize:vertical;"></textarea>\' +',
    '          \'<button id="wb-res-run-extract" class="btn">⚡ Extract Content</button>\' +',
    '        \'</div>\' +',
    '      \'</div>\' +',
    '      \'<div class="wb-research-card">\' +',
    '        \'<div class="wb-research-section-head">\' +',
    '          \'<div>\' +',
    '            \'<div class="section-title">Execution Trace & Evidence Inspector</div>\' +',
    '            \'<div class="section-note">Live multi-phase execution trace and retrieved citation evidence.</div>\' +',
    '          \'</div>\' +',
    '          \'<span id="wb-res-search-badge" class="pill">Idle</span>\' +',
    '        \'</div>\' +',
    '        \'<div id="wb-res-trace-container" style="margin-bottom:14px;max-height:220px;overflow-y:auto;">\' +',
    '          \'<div class="empty">Execution trace will stream here when search runs...</div>\' +',
    '        \'</div>\' +',
    '        \'<div class="section-title" style="font-size:13px;margin-bottom:8px;">Retrieved Sources & Evidence</div>\' +',
    '        \'<div id="wb-res-results-container" style="max-height:480px;overflow-y:auto;">\' +',
    '          \'<div class="empty">No search results yet. Enter a query and click "Run Live Search".</div>\' +',
    '        \'</div>\' +',
    '      \'</div>\' +',
    '    \'</div>\';',
    '    researchView.appendChild(wrap);',
    '    wireResearchEvents();',
    '  }',
    '  const $ = (id) => document.getElementById(id);',
    '  const esc = (s) => String(s ?? "").replace(/[&<>"\']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",\'"\':"&quot;","\'":"&#39;"}[c]));',
    '  async function apiCall(path, options) {',
    '    const r = await fetch(path, options);',
    '    const text = await r.text();',
    '    let data = {};',
    '    try { data = text ? JSON.parse(text) : {}; } catch (_) {}',
    '    if (!r.ok) throw new Error(data.error || ("HTTP " + r.status));',
    '    return data;',
    '  }',
    '  async function loadResearchTelemetryAndKeys() {',
    '    try {',
    '      const data = await apiCall("/api/dashboard/research/telemetry");',
    '      const tel = data.telemetry || {};',
    '      const pool = data.pool || {};',
    '      if ($("wb-res-req-today")) $("wb-res-req-today").textContent = tel.requestsToday || 0;',
    '      const successPct = tel.requestsToday > 0 ? Math.round(((tel.successful || 0) / tel.requestsToday) * 100) : 100;',
    '      if ($("wb-res-success-rate")) $("wb-res-success-rate").textContent = successPct + "%";',
    '      if ($("wb-res-cache-hits")) $("wb-res-cache-hits").textContent = tel.cacheHits || 0;',
    '      if ($("wb-res-cache-rate")) $("wb-res-cache-rate").textContent = (tel.cacheHitRate || 0) + "%";',
    '      if ($("wb-res-avg-lat")) $("wb-res-avg-lat").textContent = (tel.avgLatencyMs || 0) + "ms";',
    '      if ($("wb-res-p95-lat")) $("wb-res-p95-lat").textContent = (tel.p95LatencyMs || 0) + "ms";',
    '      const pStatus = tel.providerStatus || (data.isConfigured ? "healthy" : "unconfigured");',
    '      if ($("wb-res-provider-status")) {',
    '        $("wb-res-provider-status").innerHTML = pStatus === "healthy" ? \'<span class="pill good">Healthy</span>\' : (pStatus === "degraded" ? \'<span class="pill warn">Degraded</span>\' : \'<span class="pill bad">Unconfigured</span>\');',
    '      }',
    '      if ($("wb-tavily-rotation-mode")) $("wb-tavily-rotation-mode").value = pool.rotationMode || "round_robin";',
    '      renderTavilyKeys(pool.keys || []);',
    '    } catch (err) { console.warn("Failed to load research telemetry:", err); }',
    '  }',
    '  function renderTavilyKeys(keys) {',
    '    const list = $("wb-tavily-keys-list");',
    '    if (!list) return;',
    '    if (!keys || !keys.length) {',
    '      list.innerHTML = \'<div class="empty">No Tavily API keys configured in pool. Add one above to enable live web research.</div>\';',
    '      return;',
    '    }',
    '    list.innerHTML = keys.map(k => {',
    '      let statusHtml = \'<span class="pill good">Healthy</span>\';',
    '      if (k.status === "cooldown") statusHtml = \'<span class="pill warn">Cooldown (\' + k.cooldownSecondsLeft + \'s)</span>\';',
    '      else if (k.status === "disabled") statusHtml = \'<span class="pill">Disabled</span>\';',
    '      else if (k.status === "invalid") statusHtml = \'<span class="pill bad">Invalid</span>\';',
    '      return \'<div class="wb-research-key-row">\' +',
    '        \'<div><strong>\' + esc(k.name) + \'</strong><span class="mono" style="margin-left:8px;color:var(--muted);">\' + esc(k.maskedKey) + \'</span><span style="margin-left:8px;">\' + statusHtml + \'</span></div>\' +',
    '        \'<div style="display:flex;gap:8px;align-items:center;"><span style="font-size:11px;color:var(--muted);">\' + (k.totalSuccess || 0) + \' reqs • \' + (k.avgLatencyMs ? k.avgLatencyMs + \'ms\' : "—") + \'</span>\' +',
    '        \'<button class="btn" onclick="testTavilyKey(\\\'\' + esc(k.id) + \'\\\')">⚡ Test</button>\' +',
    '        \'<button class="btn" onclick="toggleTavilyKey(\\\'\' + esc(k.id) + \'\\\')">\' + (k.status === "disabled" ? "Enable" : "Disable") + \'</button>\' +',
    '        \'<button class="btn danger" onclick="deleteTavilyKey(\\\'\' + esc(k.id) + \'\\\')">Delete</button></div></div>\';',
    '    }).join("");',
    '  }',
    '  window.testTavilyKey = async function(keyId) {',
    '    try {',
    '      const res = await apiCall("/api/provider-keys/tavily/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ keyId }) });',
    '      if (res.ok) window.toast?.("Tavily Key verified! Latency: " + res.latencyMs + "ms");',
    '      else window.toast?.("Key test failed: " + (res.error || "Unknown error"), true);',
    '      loadResearchTelemetryAndKeys();',
    '    } catch (e) { window.toast?.("Test failed: " + e.message, true); }',
    '  };',
    '  window.toggleTavilyKey = async function(keyId) {',
    '    try {',
    '      await apiCall("/api/provider-keys/" + encodeURIComponent(keyId) + "/toggle", { method: "POST" });',
    '      window.toast?.("Key state updated");',
    '      loadResearchTelemetryAndKeys();',
    '    } catch (e) { window.toast?.("Toggle failed: " + e.message, true); }',
    '  };',
    '  window.deleteTavilyKey = async function(keyId) {',
    '    if (!confirm("Are you sure you want to remove this Tavily API key?")) return;',
    '    try {',
    '      await apiCall("/api/provider-keys/" + encodeURIComponent(keyId), { method: "DELETE" });',
    '      window.toast?.("Tavily key removed");',
    '      loadResearchTelemetryAndKeys();',
    '    } catch (e) { window.toast?.("Delete failed: " + e.message, true); }',
    '  };',
    '  function wireResearchEvents() {',
    '    $("wb-res-refresh-telemetry")?.addEventListener("click", () => { loadResearchTelemetryAndKeys(); window.toast?.("Research telemetry refreshed"); });',
    '    $("wb-tavily-save-rotation")?.addEventListener("click", async () => {',
    '      const mode = $("wb-tavily-rotation-mode")?.value;',
    '      try {',
    '        await apiCall("/api/provider-keys/rotation-mode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) });',
    '        window.toast?.("Tavily rotation mode saved: " + mode);',
    '      } catch (e) { window.toast?.("Failed to save mode: " + e.message, true); }',
    '    });',
    '    $("wb-tavily-test-btn")?.addEventListener("click", async () => {',
    '      const key = $("wb-tavily-new-key")?.value.trim();',
    '      const resBox = $("wb-tavily-key-test-result");',
    '      if (!key) { window.toast?.("Please enter a Tavily API key to test", true); return; }',
    '      if (resBox) { resBox.style.display = "block"; resBox.className = "pill"; resBox.textContent = "Testing credential against Tavily API..."; }',
    '      try {',
    '        const res = await apiCall("/api/provider-keys/tavily/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key }) });',
    '        if (resBox) {',
    '          if (res.ok) { resBox.className = "pill good"; resBox.textContent = "✓ Tavily API Key valid! Response latency: " + res.latencyMs + "ms"; }',
    '          else { resBox.className = "pill bad"; resBox.textContent = "✗ Invalid credential: " + (res.error || "HTTP error"); }',
    '        }',
    '      } catch (e) { if (resBox) { resBox.className = "pill bad"; resBox.textContent = "✗ Error testing key: " + e.message; } }',
    '    });',
    '    $("wb-tavily-add-btn")?.addEventListener("click", async () => {',
    '      const key = $("wb-tavily-new-key")?.value.trim();',
    '      const name = $("wb-tavily-new-name")?.value.trim() || "Tavily Key";',
    '      if (!key) { window.toast?.("Please enter a Tavily API key", true); return; }',
    '      try {',
    '        const testRes = await apiCall("/api/provider-keys/tavily/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key }) });',
    '        if (!testRes.ok) { window.toast?.("Cannot save invalid key: " + (testRes.error || "Validation failed"), true); return; }',
    '        await apiCall("/api/provider-keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: "tavily", key, name }) });',
    '        if ($("wb-tavily-new-key")) $("wb-tavily-new-key").value = "";',
    '        if ($("wb-tavily-new-name")) $("wb-tavily-new-name").value = "";',
    '        if ($("wb-tavily-key-test-result")) $("wb-tavily-key-test-result").style.display = "none";',
    '        window.toast?.("Tavily API key tested, encrypted, and saved!");',
    '        loadResearchTelemetryAndKeys();',
    '      } catch (e) { window.toast?.("Failed to save Tavily key: " + e.message, true); }',
    '    });',
    '    $("wb-res-run-search")?.addEventListener("click", async () => {',
    '      const query = $("wb-res-query")?.value.trim();',
    '      if (!query) { window.toast?.("Please enter a search query", true); return; }',
    '      const badge = $("wb-res-search-badge");',
    '      const traceBox = $("wb-res-trace-container");',
    '      const resultsBox = $("wb-res-results-container");',
    '      if (badge) { badge.className = "pill warn"; badge.textContent = "Executing Search..."; }',
    '      if (traceBox) traceBox.innerHTML = \'<div class="empty">Dispatching search request to Tavily service...</div>\';',
    '      if (resultsBox) resultsBox.innerHTML = \'<div class="empty">Retrieving and parsing evidence...</div>\';',
    '      const searchDepth = $("wb-res-depth")?.value;',
    '      const topic = $("wb-res-topic")?.value;',
    '      const maxResults = parseInt($("wb-res-max-results")?.value, 10) || 5;',
    '      const timeRange = $("wb-res-timerange")?.value || undefined;',
    '      const includeDomains = ($("wb-res-inc-domains")?.value || "").split(",").map(s => s.trim()).filter(Boolean);',
    '      const excludeDomains = ($("wb-res-exc-domains")?.value || "").split(",").map(s => s.trim()).filter(Boolean);',
    '      try {',
    '        const res = await apiCall("/api/dashboard/research/search", {',
    '          method: "POST",',
    '          headers: { "Content-Type": "application/json" },',
    '          body: JSON.stringify({',
    '            query, searchDepth, topic, maxResults, timeRange,',
    '            includeDomains: includeDomains.length ? includeDomains : undefined,',
    '            excludeDomains: excludeDomains.length ? excludeDomains : undefined',
    '          })',
    '        });',
    '        if (badge) { badge.className = "pill good"; badge.textContent = "Completed (" + (res.latencyMs || 0) + "ms)"; }',
    '        const trace = res.trace || [];',
    '        if (traceBox) {',
    '          traceBox.innerHTML = trace.map(t => \'<div class="wb-research-trace-step"><div style="font-weight:600;min-width:180px;color:#93c5fd;">\' + esc(t.phase) + \'</div><div style="flex:1;color:var(--text);">\' + esc(t.description) + \'</div>\' + (t.durationMs ? \'<div style="color:var(--muted);">\' + t.durationMs + \'ms</div>\' : "") + \'</div>\').join("");',
    '        }',
    '        const results = res.result?.results || [];',
    '        if (resultsBox) {',
    '          if (!results.length) {',
    '            resultsBox.innerHTML = \'<div class="empty">No search results returned for query.</div>\';',
    '          } else {',
    '            resultsBox.innerHTML = results.map((r, i) => \'<div class="wb-research-result-item"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:8px;"><a href="\' + esc(r.url) + \'" target="_blank" rel="noopener noreferrer" class="wb-research-result-title">[\' + (i + 1) + \'] \' + esc(r.title) + \'</a>\' + (r.score ? \'<span class="pill" style="font-size:10px;">Score: \' + Math.round(r.score * 100) + \'%</span>\' : "") + \'</div><div class="wb-research-result-url">\' + esc(r.url) + \'</div><div class="wb-research-result-snippet">\' + esc(r.content) + \'</div>\' + (r.publishedDate ? \'<div style="font-size:10px;color:var(--muted);margin-top:6px;">Published: \' + esc(r.publishedDate) + \'</div>\' : "") + \'</div>\').join("");',
    '          }',
    '        }',
    '        loadResearchTelemetryAndKeys();',
    '        window.toast?.("Live search completed with " + results.length + " sources");',
    '      } catch (e) {',
    '        if (badge) { badge.className = "pill bad"; badge.textContent = "Failed"; }',
    '        if (traceBox) traceBox.innerHTML = \'<div class="empty" style="color:#ef4444;">Search execution failed: \' + esc(e.message) + \'</div>\';',
    '        if (resultsBox) resultsBox.innerHTML = \'<div class="empty">No results due to failure.</div>\';',
    '        window.toast?.("Search failed: " + e.message, true);',
    '      }',
    '    });',
    '    $("wb-res-run-extract")?.addEventListener("click", async () => {',
    '      const rawUrls = $("wb-res-extract-urls")?.value.trim();',
    '      if (!rawUrls) { window.toast?.("Please enter at least one URL to extract", true); return; }',
    '      const urls = rawUrls.split(/[,\\n]+/).map(s => s.trim()).filter(Boolean);',
    '      const resultsBox = $("wb-res-results-container");',
    '      const badge = $("wb-res-search-badge");',
    '      if (badge) { badge.className = "pill warn"; badge.textContent = "Extracting URLs..."; }',
    '      if (resultsBox) resultsBox.innerHTML = \'<div class="empty">Extracting raw content via production Tavily service...</div>\';',
    '      try {',
    '        const res = await apiCall("/api/dashboard/research/extract", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ urls }) });',
    '        if (badge) { badge.className = "pill good"; badge.textContent = "Extracted (" + (res.latencyMs || 0) + "ms)"; }',
    '        const extracted = res.result?.results || [];',
    '        if (resultsBox) {',
    '          if (!extracted.length) resultsBox.innerHTML = \'<div class="empty">No content extracted from provided URLs.</div>\';',
    '          else {',
    '            resultsBox.innerHTML = extracted.map((item, idx) => \'<div class="wb-research-result-item"><div class="wb-research-result-title">Extracted Document [\' + (idx + 1) + \']</div><div class="wb-research-result-url">\' + esc(item.url) + \'</div><div class="wb-research-result-snippet" style="max-height:200px;overflow-y:auto;white-space:pre-wrap;font-family:monospace;font-size:11px;background:#050d18;padding:8px;border-radius:6px;">\' + esc(item.rawContent) + \'</div></div>\').join("");',
    '          }',
    '        }',
    '        window.toast?.("Extracted " + extracted.length + " documents");',
    '      } catch (e) {',
    '        if (badge) { badge.className = "pill bad"; badge.textContent = "Extraction Failed"; }',
    '        if (resultsBox) resultsBox.innerHTML = \'<div class="empty" style="color:#ef4444;">Extraction failed: \' + esc(e.message) + \'</div>\';',
    '        window.toast?.("Extraction failed: " + e.message, true);',
    '      }',
    '    });',
    '  }',
    '  document.addEventListener("DOMContentLoaded", () => { mountResearchControlPlane(); loadResearchTelemetryAndKeys(); });',
    '  if (document.readyState === "complete" || document.readyState === "interactive") { mountResearchControlPlane(); loadResearchTelemetryAndKeys(); }',
    '  const origShowView = window.showView;',
    '  if (typeof origShowView === "function") {',
    '    window.showView = function(view) {',
    '      origShowView(view);',
    '      if (view === "research") { mountResearchControlPlane(); loadResearchTelemetryAndKeys(); }',
    '    };',
    '  }',
    '})();',
    '</script>'
  ].join('\n');
}
