export function renderDashboardBehaviorControls(): string {
  return String.raw`
<style>
.wb-beh{margin-top:16px}.wb-beh-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.wb-beh-tab.active{outline:2px solid var(--blue)}.wb-beh-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wb-beh-item{padding:12px;border:1px solid var(--line);border-radius:11px;background:#0a1626}.wb-beh-item h4{margin:0 0 4px}.wb-beh-item p{margin:3px 0;color:var(--muted);font-size:12px}.wb-beh-editor{display:grid;gap:8px;margin-top:10px}.wb-beh-editor textarea{min-height:120px;resize:vertical}.wb-beh-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}@media(max-width:760px){.wb-beh-grid{grid-template-columns:1fr}}
</style>
<script>
(function(){
  let behaviors=[]; let selected=null;
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  async function api(u,o){const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function toast(msg){const e=document.getElementById('wbBehToast');if(!e)return;e.textContent=msg;e.style.display='block';setTimeout(()=>e.style.display='none',3500)}
  async function load(kind){const root=document.getElementById('wbBehavior');if(!root)return;try{behaviors=await api('/api/behaviors?kind='+encodeURIComponent(kind));render(kind)}catch(e){root.querySelector('[data-beh-status]').textContent='Unable to load configuration: '+e.message}}
  function render(kind){const root=document.getElementById('wbBehavior');const list=root.querySelector('[data-beh-list]');list.innerHTML=behaviors.map(b=>'<div class="wb-beh-item"><h4>'+esc(b.label)+(b.isDefault?' <span class="pill good">Default</span>':'')+'</h4><p>'+esc(b.description)+'</p><div class="wb-beh-actions"><button class="btn" data-edit="'+esc(b.key)+'">Configure</button>'+(b.isDefault?'':'<button class="btn" data-default="'+esc(b.key)+'">Set default</button>')+'</div></div>').join('')||'<div class="empty">No profiles found.</div>';root.querySelector('[data-beh-status]').textContent='PostgreSQL-backed configuration · '+behaviors.length+' '+kind+' profiles';}
  function openEditor(key,kind){selected=behaviors.find(b=>b.key===key);if(!selected)return;const cfg=typeof selected.config==='string'?JSON.parse(selected.config):selected.config||{};document.getElementById('wbBehKey').textContent=selected.key;document.getElementById('wbBehLabel').value=cfg.label??selected.label;document.getElementById('wbBehDescription').value=cfg.description??selected.description;document.getElementById('wbBehInstruction').value=cfg.instruction??cfg.systemBehavior??'';document.getElementById('wbBehJson').value=JSON.stringify(cfg,null,2);document.getElementById('wbBehEditor').style.display='grid';document.getElementById('wbBehEditor').dataset.kind=kind}
  async function save(){if(!selected)return;const kind=document.getElementById('wbBehEditor').dataset.kind;let json;try{json=JSON.parse(document.getElementById('wbBehJson').value||'{}')}catch(e){toast('Invalid JSON configuration');return}json.label=document.getElementById('wbBehLabel').value.trim()||selected.label;json.description=document.getElementById('wbBehDescription').value.trim()||selected.description;if(kind==='personality')json.instruction=document.getElementById('wbBehInstruction').value;else {json.systemBehavior=document.getElementById('wbBehInstruction').value;json.instruction=document.getElementById('wbBehInstruction').value}try{await api('/api/behaviors/'+encodeURIComponent(kind)+'/'+encodeURIComponent(selected.key),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(json)});toast('✓ Configuration saved to PostgreSQL and applied to runtime');document.getElementById('wbBehEditor').style.display='none';await load(kind)}catch(e){toast('Save failed: '+e.message)}}
  async function makeDefault(){if(!selected)return;const kind=document.getElementById('wbBehEditor').dataset.kind;try{await api('/api/behaviors/'+encodeURIComponent(kind)+'/'+encodeURIComponent(selected.key)+'/default',{method:'POST'});toast('✓ Default persisted');document.getElementById('wbBehEditor').style.display='none';await load(kind)}catch(e){toast('Default update failed: '+e.message)}}
  document.addEventListener('click',e=>{const t=e.target;if(t.matches('[data-edit]'))openEditor(t.dataset.edit,document.getElementById('wbBehaviorKind').value);if(t.matches('[data-default]')){selected=behaviors.find(b=>b.key===t.dataset.default);document.getElementById('wbBehEditor').dataset.kind=document.getElementById('wbBehaviorKind').value;makeDefault()};if(t.matches('[data-beh-save]'))save();if(t.matches('[data-beh-cancel]'))document.getElementById('wbBehEditor').style.display='none';if(t.matches('[data-beh-default-editor]'))makeDefault()});
  document.addEventListener('DOMContentLoaded',()=>{const models=document.getElementById('view-models');if(models&&!document.getElementById('wbBehavior')){const wrap=document.createElement('div');wrap.id='wbBehavior';wrap.className='card wb-beh';wrap.innerHTML='<div class="section-head"><div><div class="section-title">🎭 AI Personality & Operating Mode Configurator</div><div class="section-note" data-beh-status>Loading...</div></div><select id="wbBehaviorKind" class="select" style="width:auto"><option value="personality">Personality</option><option value="mode">Operating Mode</option></select></div><div class="notice">Edits are persisted in PostgreSQL and hydrated into the runtime. The Dashboard never becomes a second source of truth.</div><div class="wb-beh-grid" data-beh-list></div><div id="wbBehEditor" class="wb-beh-editor" style="display:none"><div><strong id="wbBehKey"></strong></div><input id="wbBehLabel" class="input" placeholder="Label"><input id="wbBehDescription" class="input" placeholder="Description"><textarea id="wbBehInstruction" class="input" placeholder="Behavior instruction"></textarea><textarea id="wbBehJson" class="input" spellcheck="false" placeholder="Advanced JSON configuration"></textarea><div class="wb-beh-actions"><button class="btn primary" data-beh-save>Save & apply</button><button class="btn" data-beh-default-editor>Set as default</button><button class="btn" data-beh-cancel>Cancel</button></div></div><div id="wbBehToast" class="notice" style="display:none;position:fixed;right:14px;bottom:14px;z-index:99"></div>';const anchor=models.firstElementChild;models.insertBefore(wrap,anchor||null);document.getElementById('wbBehaviorKind').addEventListener('change',e=>{document.getElementById('wbBehEditor').style.display='none';load(e.target.value)});load('personality')}})();
})();
</script>`;
}
