export function renderDashboardAIRoutingControls(): string {
  return `
<section id="ai-routing-control-plane" style="margin:24px 0;padding:20px;border:1px solid rgba(148,163,184,.22);border-radius:18px;background:rgba(15,23,42,.55);color:#e5e7eb;font-family:system-ui,sans-serif">
  <div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap">
    <div><h2 style="margin:0 0 6px;font-size:20px">AI Providers & Adaptive Routing</h2><p style="margin:0;color:#94a3b8;font-size:13px">PostgreSQL-backed provider/model control plane. Runtime routing hot-reads these controls.</p></div>
    <button id="air-refresh" style="padding:9px 13px;border:1px solid #334155;border-radius:10px;background:#111827;color:#e5e7eb;cursor:pointer">Refresh</button>
  </div>
  <div id="air-status" style="margin-top:12px;font-size:13px;color:#94a3b8"></div>
  <div id="air-providers" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px;margin-top:16px"></div>
  <div style="display:flex;gap:12px;flex-wrap:wrap;margin-top:18px">
    <div style="flex:1 1 620px;min-width:0"><h3 style="font-size:15px;margin:0 0 10px">Registered Models</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:8px">Provider</th><th style="text-align:left;padding:8px">Model</th><th style="text-align:left;padding:8px">Roles</th><th style="padding:8px">State</th><th style="padding:8px">Action</th></tr></thead><tbody id="air-models"></tbody></table></div></div>
    <div style="flex:0 1 320px"><h3 style="font-size:15px;margin:0 0 10px">Add model</h3><div style="display:grid;gap:8px"><select id="air-provider" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"><option value="gemini">Gemini</option><option value="groq">Groq</option><option value="mistral">Mistral</option></select><input id="air-model-id" placeholder="Provider model ID" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-model-name" placeholder="Display name (optional)" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-model-capabilities" placeholder="Capabilities, comma separated" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><select id="air-model-role" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"><option value="">General</option><option value="fast">Fast</option><option value="reasoning">Reasoning</option><option value="extraction">Extraction</option></select><button id="air-add-model" style="padding:10px;border:0;border-radius:10px;background:#2563eb;color:white;cursor:pointer">Register model</button></div></div>
  </div>
  <div style="margin-top:18px"><h3 style="font-size:15px;margin:0 0 10px">Routing policy</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px"><select id="air-strategy" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"><option value="adaptive">Adaptive</option><option value="primary_first">Primary first</option><option value="priority_only">Priority only</option></select><input id="air-cap" type="number" min="0" max="100" placeholder="Capability weight" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-health" type="number" min="0" max="100" placeholder="Health weight" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-latency" type="number" min="0" max="100" placeholder="Latency weight" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-priority" type="number" min="0" max="100" placeholder="Priority weight" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><input id="air-attempts" type="number" min="1" max="6" placeholder="Max attempts" style="padding:9px;border-radius:9px;background:#0f172a;color:#e5e7eb;border:1px solid #334155"/><button id="air-save-policy" style="padding:10px;border:0;border-radius:10px;background:#16a34a;color:white;cursor:pointer">Save policy</button></div></div>
  <div id="air-health" style="margin-top:18px"></div>
</section>
<script>
(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function json(url, options) { const r = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); const body = await r.json(); if(!r.ok) throw new Error(body.error || 'Request failed'); return body; }
  async function load() {
    $('air-status').textContent = 'Loading AI control plane…';
    try {
      const [providers, models, policy, health] = await Promise.all([json('/api/providers'), json('/api/models'), json('/api/ai/routing/policy'), json('/api/ai/routing/health')]);
      $('air-providers').innerHTML = providers.providers.map(p => '<div style="padding:12px;border:1px solid #334155;border-radius:12px;background:#0b1220"><div style="font-weight:700">'+esc(p.name)+'</div><div style="font-size:12px;color:#94a3b8;margin-top:3px">'+esc(p.id)+' · '+(p.adapterAvailable ? 'adapter ready' : 'adapter missing')+'</div><div style="margin-top:7px"><span style="color:'+(p.enabled && p.configured ? '#4ade80':'#fbbf24')+'">● '+(p.enabled && p.configured ? 'Ready':'Not ready')+'</span></div><div style="margin-top:7px"><button data-provider="'+esc(p.id)+'" class="air-toggle" style="padding:6px 9px;border-radius:8px;border:1px solid #334155;background:#111827;color:#e5e7eb;cursor:pointer">'+(p.enabled?'Disable':'Enable')+'</button><button data-test-provider="'+esc(p.id)+'" style="padding:6px 9px;margin-left:6px;border-radius:8px;border:1px solid #334155;background:#111827;color:#e5e7eb;cursor:pointer">Test</button></div></div>').join('');
      $('air-models').innerHTML = models.models.length ? models.models.map(m => '<tr style="border-top:1px solid #1e293b"><td style="padding:8px">'+esc(m.provider)+'</td><td style="padding:8px"><div>'+esc(m.name)+'</div><div style="font-size:11px;color:#94a3b8">'+esc(m.modelId)+'</div></td><td style="padding:8px">'+esc(m.roles.join(', ') || 'general')+'</td><td style="padding:8px;text-align:center">'+(m.enabled?'✓':'—')+'</td><td style="padding:8px;text-align:center">'+(m.roles.includes('primary')?'<span style="font-size:11px">PRIMARY</span>':'<button class="air-primary" data-id="'+esc(m.id)+'" style="padding:6px 8px;border-radius:8px;border:1px solid #334155;background:#111827;color:#e5e7eb;cursor:pointer">Set primary</button>')+'</td></tr>').join('') : '<tr><td colspan="5" style="padding:12px;color:#94a3b8">No registered models yet.</td></tr>';
      $('air-strategy').value = policy.policy.strategy; $('air-cap').value = policy.policy.capabilityWeight; $('air-health').value = policy.policy.healthWeight; $('air-latency').value = policy.policy.latencyWeight; $('air-priority').value = policy.policy.priorityWeight; $('air-attempts').value = policy.policy.maxAttempts;
      $('air-health').innerHTML = '<h3 style="font-size:15px;margin:0 0 8px">Adaptive health</h3>'+health.health.map(h => '<div style="display:inline-block;min-width:220px;margin:0 8px 8px 0;padding:10px;border:1px solid #1e293b;border-radius:10px"><div>'+esc(h.provider)+' / '+esc(h.modelId)+'</div><div style="font-size:12px;color:#94a3b8">Health '+h.healthScore+' · EWMA '+h.ewmaLatencyMs+'ms · ✓ '+h.successes+' / ✕ '+h.failures+'</div></div>').join('');
      $('air-status').textContent = 'Primary: '+(models.models.find(m=>m.roles.includes('primary'))?.provider || 'not set')+' / '+(models.models.find(m=>m.roles.includes('primary'))?.modelId || 'not set')+' · Strategy: '+policy.policy.strategy;
      document.querySelectorAll('.air-toggle').forEach(b => b.onclick = async () => { const p = providers.providers.find(x=>x.id===b.dataset.provider); await json('/api/providers/'+encodeURIComponent(b.dataset.provider), {method:'PATCH',body:JSON.stringify({enabled:!p.enabled})}); load(); });
      document.querySelectorAll('[data-test-provider]').forEach(b => b.onclick = async () => { const p = providers.providers.find(x=>x.id===b.dataset.testProvider); const m = models.models.find(x=>x.provider===p.id); if(!m) return alert('Register a model for this provider first.'); const result = await json('/api/providers/'+encodeURIComponent(p.id)+'/test',{method:'POST',body:JSON.stringify({model:m.modelId})}); alert(result.ok?'Provider test passed in '+result.latencyMs+'ms':('Provider test failed: '+result.error)); });
      document.querySelectorAll('.air-primary').forEach(b => b.onclick = async () => { await json('/api/models/'+encodeURIComponent(b.dataset.id)+'/primary',{method:'POST',body:'{}'}); load(); });
    } catch (e) { $('air-status').textContent = 'Error: '+e.message; }
  }
  $('air-refresh').onclick = load;
  $('air-add-model').onclick = async () => { try { const role=$('air-model-role').value; await json('/api/models',{method:'POST',body:JSON.stringify({provider:$('air-provider').value,modelId:$('air-model-id').value,name:$('air-model-name').value,roles:role?[role]:[],capabilities:$('air-model-capabilities').value.split(',').map(x=>x.trim()).filter(Boolean)})}); $('air-model-id').value='';$('air-model-name').value='';load(); } catch(e){alert(e.message);} };
  $('air-save-policy').onclick = async () => { try { await json('/api/ai/routing/policy',{method:'PATCH',body:JSON.stringify({strategy:$('air-strategy').value,capabilityWeight:Number($('air-cap').value),healthWeight:Number($('air-health').value),latencyWeight:Number($('air-latency').value),priorityWeight:Number($('air-priority').value),maxAttempts:Number($('air-attempts').value)})}); load(); } catch(e){alert(e.message);} };
  load();
})();
</script>`;
}
