export function renderDashboardProviderKeyControls(): string {
  return String.raw`
<section id="provider-key-control-plane" style="margin:24px 0;padding:20px;border:1px solid var(--line);border-radius:18px;background:var(--panel);color:var(--text);font-family:system-ui,sans-serif">
  <div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap">
    <div><h2 style="margin:0 0 6px;font-size:20px">Provider API Key Pools</h2><p style="margin:0;color:var(--muted);font-size:13px">Manage multiple encrypted API keys per provider. Rotation and failover happen below model/provider routing.</p></div>
    <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><select id="pk-mode" style="padding:8px;border-radius:9px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"><option value="round_robin">Round robin</option><option value="failover">Failover</option></select><button id="pk-mode-save" style="padding:8px 11px;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);cursor:pointer">Save rotation</button><button id="pk-refresh" style="padding:8px 11px;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);cursor:pointer">Refresh</button></div>
  </div>
  <div id="pk-status" style="margin-top:12px;font-size:13px;color:var(--muted)"></div>
  <div id="pk-providers" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:12px;margin-top:16px"></div>
</section>
<script>
(() => {
  const $ = (id) => document.getElementById(id);
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const previewCatalogs = new Map();
  async function json(url, options){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Request failed');return b;}
  async function storedCatalogFor(provider){try{const d=await json('/api/models/catalog/'+encodeURIComponent(provider));return d.models||[]}catch{return []}}
  function populateModelOptions(id, models){const select=$('pk-model-'+id);if(!select)return;select.innerHTML=models.length?models.filter(m=>!(m.capabilities||[]).some(c=>String(c).toLowerCase().includes('embedding'))).map(m=>'<option value="'+esc(m.modelId)+'">'+esc(m.name||m.modelId)+' · '+esc(m.modelId)+'</option>').join(''):'<option value="">No model available</option>';}
  async function previewModels(provider){const key=$('pk-key-'+provider).value.trim();if(!key){alert('Enter the API key first.');return}const status=$('pk-catalog-status-'+provider);status.textContent='Fetching live models using the entered key…';try{const d=await json('/api/models/catalog/preview',{method:'POST',body:JSON.stringify({provider,apiKey:key})});previewCatalogs.set(provider,d.models||[]);populateModelOptions(provider,d.models||[]);status.textContent=(d.models||[]).length+' live models discovered from this key.'; }catch(e){status.textContent='Model discovery failed: '+e.message;alert(e.message)}}
  async function load(){
    $('pk-status').textContent='Refreshing provider key pools and live model catalogs…';
    try{
      const [providers, summaries, models]=await Promise.all([json('/api/providers'),json('/api/provider-keys/summary/all'),json('/api/models')]);
      const registeredByProvider=new Map(); (models.models||[]).forEach(m=>{if(!registeredByProvider.has(m.provider))registeredByProvider.set(m.provider,[]);registeredByProvider.get(m.provider).push(m)});
      const catalogs=await Promise.all((providers.providers||[]).map(async p=>[p.id,await storedCatalogFor(p.id)])); const catalogByProvider=new Map(catalogs);
      const entries=(providers.providers||[]).map(p=>{
        const pool=summaries.providers[p.id]||{provider:p.id,totalKeys:0,healthyKeys:0,inCooldownKeys:0,disabledKeys:0,invalidKeys:0,keys:[]};
        const live=catalogByProvider.get(p.id)||[]; const registered=registeredByProvider.get(p.id)||[]; const combined=new Map(); [...live,...registered.map(m=>({provider:p.id,modelId:m.modelId,name:m.name,capabilities:m.capabilities||[],status:'registered'}))].forEach(m=>{if(m.modelId&&!combined.has(m.modelId))combined.set(m.modelId,m)});
        const options=[...combined.values()].filter(m=>!((m.capabilities||[]).some(c=>String(c).toLowerCase().includes('embedding')))).sort((a,b)=>String(a.name||a.modelId).localeCompare(String(b.name||b.modelId))).map(m=>'<option value="'+esc(m.modelId)+'">'+esc(m.name||m.modelId)+' · '+esc(m.modelId)+'</option>').join('');
        const requiresModel = (p.capabilities || []).includes('chat');
        const modelFields = requiresModel
          ? '<button data-pk-discover="'+esc(p.id)+'" style="padding:8px;border-radius:8px;border:1px solid var(--line);background:var(--panel-2);color:var(--text);cursor:pointer;grid-column:1/-1">Load live models from this key</button><select id="pk-model-'+esc(p.id)+'" style="padding:8px;border-radius:8px;background:var(--panel-3);color:var(--text);border:1px solid var(--line);grid-column:1/-1">'+(options||'<option value="">Load live models first</option>')+'</select><div id="pk-catalog-status-'+esc(p.id)+'" style="grid-column:1/-1;color:var(--muted);font-size:11px">'+(live.length?'Live provider catalog available.':'Enter a key and load its live model catalog before adding the first key.')+'</div>'
          : '<div style="grid-column:1/-1;padding:7px 9px;border-radius:8px;background:var(--panel-3);border:1px solid var(--line);color:var(--muted);font-size:11px">Direct endpoint authentication ('+esc((p.capabilities||[]).join(', '))+'). Validates API key directly without model selection.</div>';
        return '<div style="padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--panel)"><div style="display:flex;justify-content:space-between;gap:10px"><strong>'+esc(p.name)+'</strong><span style="font-size:11px;color:'+(p.enabled&&p.configured?'var(--success)':'var(--warning)')+'">'+(p.enabled&&p.configured?'READY':'NOT READY')+'</span></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px;font-size:11px"><div><span style="color:var(--muted)">Total</span><br><b>'+pool.totalKeys+'</b></div><div><span style="color:var(--muted)">Healthy</span><br><b>'+pool.healthyKeys+'</b></div><div><span style="color:var(--muted)">Cooldown</span><br><b>'+pool.inCooldownKeys+'</b></div><div><span style="color:var(--muted)">Invalid</span><br><b>'+pool.invalidKeys+'</b></div></div><div style="margin-top:10px;display:grid;gap:7px">'+(pool.keys.length?pool.keys.map(k=>'<div style="display:flex;justify-content:space-between;gap:7px;align-items:center;padding:7px 8px;border:1px solid var(--line);border-radius:9px"><div><b>'+esc(k.name)+'</b><div style="font:11px ui-monospace;color:var(--muted)">'+esc(k.maskedKey)+'</div></div><span style="font-size:11px">'+esc(k.status)+'</span><div style="display:flex;gap:4px"><button data-pk-toggle="'+esc(k.id)+'" style="padding:5px 7px;border-radius:7px;border:1px solid var(--line);background:var(--panel-2);color:var(--text)">'+(k.status==='disabled'?'Enable':'Disable')+'</button><button data-pk-delete="'+esc(k.id)+'" style="padding:5px 7px;border-radius:7px;border:1px solid var(--danger-border);background:var(--danger-bg);color:var(--danger)">Remove</button></div></div>').join(''):'<div style="color:var(--muted);font-size:12px">No managed keys yet.</div>')+'</div><div style="border-top:1px solid var(--line);margin-top:12px;padding-top:12px;display:grid;grid-template-columns:1fr 1fr;gap:7px"><input id="pk-name-'+esc(p.id)+'" placeholder="Key label" style="padding:8px;border-radius:8px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/><input id="pk-key-'+esc(p.id)+'" placeholder="Paste API key" type="password" autocomplete="new-password" style="padding:8px;border-radius:8px;background:var(--panel-3);color:var(--text);border:1px solid var(--line)"/>'+modelFields+'<button data-pk-add="'+esc(p.id)+'" style="padding:9px;border:0;border-radius:9px;background:var(--primary);color:var(--on-primary);cursor:pointer;grid-column:1/-1">Validate & Add Key</button></div></div>';
      }).join('');
      $('pk-providers').innerHTML=entries; $('pk-status').textContent='Encrypted provider key pools and live model catalogs loaded.';
      document.querySelectorAll('[data-pk-discover]').forEach(b=>b.onclick=()=>previewModels(b.dataset.pkDiscover));
      document.querySelectorAll('[data-pk-add]').forEach(b=>b.onclick=async()=>{try{const id=b.dataset.pkAdd;const key=$('pk-key-'+id).value.trim();const name=$('pk-name-'+id).value.trim();const modelSelect=$('pk-model-'+id);const model=modelSelect?modelSelect.value:'';if(modelSelect&&!model)throw new Error('Load and select a current model for key validation');await json('/api/provider-keys',{method:'POST',body:JSON.stringify({provider:id,key,name,model})});$('pk-key-'+id).value='';$('pk-name-'+id).value='';previewCatalogs.delete(id);await load();}catch(e){alert(e.message)}});
      document.querySelectorAll('[data-pk-toggle]').forEach(b=>b.onclick=async()=>{try{await json('/api/provider-keys/'+encodeURIComponent(b.dataset.pkToggle)+'/toggle',{method:'PATCH',body:'{}'});load();}catch(e){alert(e.message)}});
      document.querySelectorAll('[data-pk-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this provider API key?'))return;try{await json('/api/provider-keys/'+encodeURIComponent(b.dataset.pkDelete),{method:'DELETE'});load();}catch(e){alert(e.message)}});
      const first=Object.values(summaries.providers||{})[0]; if(first) $('pk-mode').value=first.rotationMode||'round_robin';
    }catch(e){$('pk-status').textContent='Error: '+e.message;}
  }
  $('pk-refresh').onclick=load;
  $('pk-mode-save').onclick=async()=>{try{await json('/api/provider-keys/mode',{method:'POST',body:JSON.stringify({mode:$('pk-mode').value})});load();}catch(e){alert(e.message)}};
  load();
})();
</script>`;
}
